"""augur tools: LSST Y1/Y10 3x2pt Fisher forecasts (augur 1.2.4 on firecrown + CCL).

Pipeline: augur_generate_forecast_config -> augur_validate_forecast_config ->
augur_generate_synthetic_datavector -> augur_compute_fisher -> augur_plot_fisher_contours.
The computation (augur.generate + augur.Analyze) lives in the env-kernel
``tools/inner/augur_forecast.py`` and runs in-process locally or under the
client's ``env_setup`` on a facility (mcp_server.dispatch.run_env_kernel).
"""

import copy
import json
import os
from pathlib import Path
from typing import Annotated, Literal

import numpy as np
from pydantic import Field, validate_call

from ..common import (ArtifactResult, clone_dir, param_slug, require_clone,
                      resolve_outdir, write_csv, write_json)
from ..cosmology import CosmologyParams

__all__ = ["augur_list_examples", "augur_generate_forecast_config",
           "augur_validate_forecast_config", "augur_generate_synthetic_datavector",
           "augur_compute_fisher", "augur_plot_fisher_contours"]

CONVENTIONS = {
    "kmax": "Mpc^-1 (NO h): augur converts kmax -> lmax = kmax * chi(z_mean) with CCL's h-free chi",
    "lmax": "dimensionless multipole; mutually exclusive with kmax per statistic",
    "ndens": "arcmin^-2, total over all bins of a tracer kind (split per bin by the n(z) integral)",
    "sigma_e": "per-component shape noise (SRD: 0.26); noise power = sigma_e^2 / nbar",
    "ells": "dimensionless; bands are geometric centres of log-spaced edges (SRD: 20 bands in 20..15000)",
    "step": "ABSOLUTE finite-difference step in parameter units (not relative); default 0.01",
    "fsky": "sky fraction for gaus_internal / tjpcov (LSST Y1 ~0.3, Y10 ~0.4)",
    "parameter_names": "firecrown/CCL: Omega_c Omega_b h n_s sigma8|A_s Omega_k Neff m_nu w0 wa; "
                       "nuisance src{i}_delta_z src{i}_mult_bias lens{i}_bias lens{i}_delta_z "
                       "lens{i}_sigma_z, global IA ia_bias alphaz z_piv",
    "fisher_units": "F_ij in (parameter units)^-2; sigma_i = sqrt((F^-1)_ii) marginalised over the rest",
    "fom": "DETF FoM = 1/sqrt(det Cov(w0,wa)); augur's get_FoM_all divides Cov by chi2.ppf(CL,2)",
    "tracer_names": "src{i} (galaxy_shear) and lens{i} (galaxy_density) - required by augur",
    "ggl_pairs": "statistics.galaxy_shearDensity_cl_e.tracer_combs are [lens_i, src_j]",
}

CAVEATS = [
    "Step sizes are absolute (passed straight to numdifftools / the 5-point stencil); the shipped SRD "
    "examples use 1e-5, which can be spline-noise dominated - 1e-2 to 1e-3 is safer for cosmology.",
    "Every gaussian_priors key must be in var_pars (or be Omega_m/S8 with the transform on) or augur "
    "raises; the shipped srd_y1/y10 examples list 30 priors for 9 varied parameters and do NOT run as is.",
    "cov_type SRD needs exactly the SRD layout (Y1: 5 source + 5 lens bins, Y10: 5 + 10), the SRD "
    "tracer-pair lists, all three statistics and 20 ell bands; anything else needs gaus_internal or tjpcov.",
    "general.ignore_scale_cuts_likelihood must stay False with a Firecrown_Factory: True silently drops "
    "all systematics from the likelihood (legacy ConstGaussian fallback).",
    "transfer_function boltzmann_camb needs cosmo.extra_parameters.camb.halofit_version; "
    "eisenstein_hu + halofit (the SRD examples) is ~5x faster per evaluation.",
    "augur mutates global pyccl spline/gsl accuracy parameters (ccl_accuracy) for the whole process.",
    "Nz_type TopHat/Gaussian are documented but not in augur's registry; use ZDist, SourceSRD2018, "
    "LensSRD2018 or ZDistFromFile.",
    "Remote runs embed the n(z) tables (and the SRD covariance, <= 6 MB) in the kernel params; the "
    "facility environment must provide augur + firecrown >= 1.14 + numdifftools.",
    "mu-Sigma modified gravity and baryonic-feedback P(k) are not generated by this tool "
    "(edit a YAML by hand after augur/examples/srd_y1_3x2_mg.yml).",
]

DISPATCH_KERNELS = {
    "augur_forecast": {
        "function": "envkernel.run_in_env",
        "inner": "augur_forecast",
        "params": {"config": "<augur config dict with absolute paths>",
                   "mode": "generate | fisher",
                   "inline_files": "{basename: {kind: ascii|npy_b64, data}} n(z) tables / SRD cov",
                   "relocate_outputs": True, "include_bias": None, "max_cov_return": 600},
        "env_setup_required": True,
        "suitable_envs": ["desc-python", "desc-cosmology"],
        "duration_hint_s": 1800,
        "returns": "data vector rows, n(z), covariance diagonal, Fisher matrix (nested lists), "
                   "fiducials, priors, derivatives, optional Fisher bias; sacc written in the job cwd",
    },
}

# ---------------------------------------------------------------------------
# SRD encodings (augur/examples/srd_y1_3x2.yml, srd_y10_3x2.yml)
# ---------------------------------------------------------------------------
SRD_PRESETS = {
    "Y1": {"n_source_bins": 5, "n_lens_bins": 5, "ndens_source": 10.0, "ndens_lens": 18.0,
           "kmax": 0.202, "fsky": 0.3,
           "lens_bias": [1.562362, 1.732963, 1.913252, 2.100644, 2.293210],
           "nz_source_file": "srd_source_bins_y1.txt", "nz_lens_file": "srd_lens_bins_y1.txt",
           "srd_cov_file": "Y1_3x2_SRD_cov.npy",
           "source_nz": {"Nz_alpha": 0.78, "Nz_z0": 0.13, "Nz_sigmaz": 0.05},
           "lens_nz": {"Nz_alpha": 0.94, "Nz_z0": 0.26, "Nz_sigmaz": 0.03, "Nz_width": 0.2,
                       "Nz_center": [0.3, 0.5, 0.7, 0.9, 1.1]},
           "ggl_pairs": [[0, 2], [0, 3], [0, 4], [1, 3], [1, 4], [2, 4], [3, 4]]},
    "Y10": {"n_source_bins": 5, "n_lens_bins": 10, "ndens_source": 27.0, "ndens_lens": 48.0,
            "kmax": 0.201, "fsky": 0.4,
            "lens_bias": [1.376695, 1.451179, 1.528404, 1.607983, 1.689579,
                          1.772899, 1.857700, 1.943754, 2.030887, 2.118943],
            "nz_source_file": "srd_source_bins_y10.txt", "nz_lens_file": "srd_lens_bins_y10.txt",
            "srd_cov_file": "Y10_3x2_SRD_cov.npy",
            "source_nz": {"Nz_alpha": 0.68, "Nz_z0": 0.11, "Nz_sigmaz": 0.05},
            "lens_nz": {"Nz_alpha": 0.90, "Nz_z0": 0.28, "Nz_sigmaz": 0.03, "Nz_width": 0.1,
                        "Nz_center": [round(0.25 + 0.1 * i, 2) for i in range(10)]},
            "ggl_pairs": [[0, 1], [0, 2], [0, 3], [0, 4], [1, 1], [1, 2], [1, 3], [1, 4],
                          [2, 2], [2, 3], [2, 4], [3, 2], [3, 3], [3, 4], [4, 2], [4, 3], [4, 4],
                          [5, 3], [5, 4], [6, 3], [6, 4], [7, 3], [7, 4], [8, 4], [9, 4]]},
}
# SRD table (p. 43) prior widths; applied only to parameters actually varied
SRD_PRIOR_WIDTHS = {"Omega_c": 0.2, "Omega_b": 0.006, "h": 0.063, "n_s": 0.08, "sigma8": 0.14,
                    "w0": 0.8, "wa": 2.0, "ia_bias": 3.9, "alphaz": 2.3}
SRD_PRIOR_PATTERNS = {"_bias": 0.9, "lens_delta_z": 0.005, "src_delta_z": 0.002, "_mult_bias": 0.013}
IA_FIDUCIAL = {"ia_bias": 5.717, "alphaz": -0.47, "z_piv": 0.3}

NZ_REGISTRY = ("ZDist", "LensSRD2018", "SourceSRD2018", "ZDistFromFile")
DATA_TYPES = {"galaxy_shear_cl_ee": ("src", "src"), "galaxy_shearDensity_cl_e": ("lens", "src"),
              "galaxy_density_cl": ("lens", "lens")}
TRANSFER_REGISTRY = ("boltzmann_camb", "boltzmann_class", "eisenstein_hu", "eh", "bbks")
COSMO_KEYS = ("Omega_c", "Omega_b", "h", "n_s", "sigma8", "A_s", "Omega_k", "Neff", "m_nu",
              "w0", "wa", "T_CMB", "mass_split")
PARAM_LABELS = {
    "Omega_c": r"$\Omega_c$", "Omega_b": r"$\Omega_b$", "Omega_m": r"$\Omega_m$", "h": r"$h$",
    "n_s": r"$n_s$", "sigma8": r"$\sigma_8$", "S8": r"$S_8$", "A_s": r"$A_s$", "w0": r"$w_0$",
    "wa": r"$w_a$", "Omega_k": r"$\Omega_k$", "m_nu": r"$\sum m_\nu$", "Neff": r"$N_{\rm eff}$",
    "ia_bias": r"$A_{\rm IA}$", "alphaz": r"$\eta_{\rm IA}$",
}

FIRECROWN_FACTORY = {
    "TwoPointFactory": {
        "correlation_space": "harmonic",
        "number_counts_factories": [{
            "type_source": "default", "global_systematics": [], "include_rsd": False,
            "per_bin_systematics": [{"type": "PhotoZShiftandStretchFactory"},
                                    {"type": "LinearBiasSystematicFactory"}]}],
        "weak_lensing_factories": [{
            "type_source": "default",
            "global_systematics": [{"type": "LinearAlignmentSystematicFactory", "alphag": 1}],
            "per_bin_systematics": [{"type": "MultiplicativeShearBiasFactory"},
                                    {"type": "PhotoZShiftFactory"}]}],
        "cmb_factories": [], "int_options": None}}


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------
def _label_of(name: str) -> str:
    if name in PARAM_LABELS:
        return PARAM_LABELS[name]
    if name.startswith(("lens", "src")) and "_" in name:
        tr, _, par = name.partition("_")
        sym = {"bias": "b", "delta_z": r"\Delta z", "sigma_z": r"\sigma_z", "mult_bias": "m"}.get(par, par)
        return rf"${sym}_{{\rm {tr}}}$"
    return name


def _augur_data_dir() -> Path:
    return require_clone("augur") / "data"


def _render_yaml_text(path: Path) -> dict:
    """Load a YAML config; render ``{{ env['AUGUR_DIR'] }}`` Jinja tags like augur's parser."""
    import yaml
    text = path.read_text(encoding="utf-8")
    if "{{" in text:
        env = dict(os.environ)
        clone = clone_dir("augur")
        if clone is not None:
            env.setdefault("AUGUR_DIR", str(clone))
        try:
            import jinja2
            text = jinja2.Template(text).render(env=env)
        except ImportError:
            text = text.replace("{{ env['AUGUR_DIR'] }}", env.get("AUGUR_DIR", ""))
    return yaml.safe_load(text)


def _load_config(config_path: str) -> dict:
    path = Path(config_path).expanduser().resolve()
    if not path.is_file():
        raise FileNotFoundError(f"config not found: {path}")
    cfg = _render_yaml_text(path)
    if not isinstance(cfg, dict):
        raise ValueError(f"{path} did not parse to a mapping")
    return cfg


def _parse_edges(value):
    from augur.utils.config_io import parse_array  # numpy-only module
    return np.asarray(parse_array(value), dtype=float)


def _pairs_all(n1: int, n2: int, symmetric: bool) -> list[list[int]]:
    if symmetric:
        return [[i, j] for i in range(n1) for j in range(i, n1)]
    return [[i, j] for i in range(n1) for j in range(n2)]


def _write_table(path: Path, header_lines: list[str], columns: dict[str, list]) -> None:
    """CSV with '# key: value' headers that allows string columns (write_csv is float-only)."""
    n = len(next(iter(columns.values())))
    with path.open("w", encoding="utf-8") as f:
        for line in header_lines:
            f.write(f"# {line}\n")
        f.write(",".join(columns.keys()) + "\n")
        for i in range(n):
            cells = []
            for v in columns.values():
                x = v[i]
                cells.append(f"{x:.8g}" if isinstance(x, (float, np.floating)) else str(x))
            f.write(",".join(cells) + "\n")


def _write_fisher_csv(path: Path, names: list[str], F: np.ndarray, fiducials: list[float],
                      priors: dict, label: str, extra: list[str]) -> None:
    header = [f"label: {label}", "quantity: fisher_matrix",
              f"params: {','.join(names)}", "units: (parameter units)^-2; rows/columns in params order"]
    header += [f"fiducial_{n}: {v:.10g}" for n, v in zip(names, fiducials)]
    header += [f"prior_{n}: {priors[n]:.6g}" for n in names if n in priors]
    header += extra
    cols = {"param": list(names)}
    for j, n in enumerate(names):
        cols[n] = [float(F[i, j]) for i in range(len(names))]
    _write_table(path, header, cols)


def read_fisher_csv(path_str: str) -> tuple[list[str], np.ndarray, dict, dict]:
    """Read a fisher.csv written here -> (names, F, fiducials{name: value}, header dict).

    Also accepts a plain whitespace matrix (augur's fisher.dat) when a
    companion ``<stem>.names`` or augur ``fiducials.dat`` is NOT available:
    names become p0..pN and fiducials 0.
    """
    path = Path(path_str).expanduser().resolve()
    lines = path.read_text(encoding="utf-8").splitlines()
    header: dict[str, str] = {}
    i = 0
    for i, line in enumerate(lines):
        if not line.startswith("#"):
            break
        key, _, value = line.lstrip("# ").partition(":")
        header[key.strip()] = value.strip()
    body = [ln for ln in lines[i:] if ln.strip()]
    if "," in body[0] and body[0].split(",")[0].strip() == "param":
        names = [c.strip() for c in body[0].split(",")[1:]]
        F = np.array([[float(x) for x in ln.split(",")[1:]] for ln in body[1:]], dtype=float)
    else:  # plain matrix
        F = np.loadtxt(body, ndmin=2)
        names = header.get("params", "").split(",") if header.get("params") else \
            [f"p{k}" for k in range(F.shape[0])]
    fid = {n: float(header.get(f"fiducial_{n}", 0.0)) for n in names}
    return names, F, fid, header


def _ellipse(cov2: np.ndarray, CL: float) -> tuple[float, float, float]:
    """(width, height, angle_deg) of the CL ellipse for a 2x2 covariance (augur's formula)."""
    from scipy.stats import chi2
    C = chi2.ppf(CL, 2) * cov2
    D = np.sqrt((C[0, 0] - C[1, 1]) ** 2 + 4 * C[0, 1] ** 2)
    w = 2 * np.sqrt(max(0.5 * (C[0, 0] + C[1, 1] + D), 0))
    h = 2 * np.sqrt(max(0.5 * (C[0, 0] + C[1, 1] - D), 0))
    ang = np.rad2deg(0.5 * np.arctan2(2 * C[0, 1], C[0, 0] - C[1, 1]))
    return float(w), float(h), float(ang)


def _fom_block(F: np.ndarray, names: list[str]) -> dict | None:
    """DETF FoM and augur's get_FoM_all for (w0, wa) when both are varied."""
    if "w0" not in names or "wa" not in names:
        return None
    iw, iwa = names.index("w0"), names.index("wa")
    cov = np.linalg.inv(F)
    sub = cov[np.ix_([iw, iwa], [iw, iwa])]
    det = float(np.linalg.det(sub))
    out = {"detf_fom": float(1.0 / np.sqrt(det)) if det > 0 else None,
           "sigma_w0": float(np.sqrt(cov[iw, iw])), "sigma_wa": float(np.sqrt(cov[iwa, iwa])),
           "rho_w0_wa": float(sub[0, 1] / np.sqrt(sub[0, 0] * sub[1, 1])),
           "augur_get_FoM_all": {}}
    try:
        from augur.postprocess import get_FoM_all
    except Exception:  # noqa: BLE001 - fall back to the same arithmetic
        from scipy.stats import chi2

        def get_FoM_all(fisher, p1, p2, CL):
            s = chi2.ppf(CL, 2)
            inv = s * np.linalg.inv(fisher)
            fom = 1.0 / np.sqrt(inv[p1, p1] * inv[p2, p2] - inv[p1, p2] * inv[p2, p1])
            fom2 = np.sqrt(np.linalg.det(np.linalg.inv(inv[np.ix_([p1, p2], [p1, p2])])))
            return fom, fom2
    for CL in (0.68, 0.95):
        fom, fom2 = get_FoM_all(F, iw, iwa, CL)
        out["augur_get_FoM_all"][f"CL{CL:g}"] = {"FoM": float(fom), "FoM_alt": float(fom2)}
    return out


def _derived_sigmas(F: np.ndarray, names: list[str], cosmo: dict) -> dict:
    """sigma(Omega_m) and sigma(S8) by linear propagation of Cov = F^-1."""
    cov = np.linalg.inv(F)
    h = float(cosmo.get("h", 0.67))
    Oc, Ob = float(cosmo.get("Omega_c", 0.25)), float(cosmo.get("Omega_b", 0.05))
    mnu = float(cosmo.get("m_nu", 0.0) or 0.0)
    Onu = mnu / (93.14 * h ** 2)
    Om = Oc + Ob + Onu
    out = {}
    g_om = np.zeros(len(names))
    for k, n in enumerate(names):
        if n == "Omega_c" or n == "Omega_b":
            g_om[k] = 1.0
        elif n == "m_nu":
            g_om[k] = 1.0 / (93.14 * h ** 2)
        elif n == "h":
            g_om[k] = -2.0 * Onu / h
    if "Omega_c" in names and "Omega_m" not in names:
        out["Omega_m"] = {"fiducial": Om, "sigma": float(np.sqrt(g_om @ cov @ g_om))}
    s8 = cosmo.get("sigma8")
    if s8 is not None and "sigma8" in names and "S8" not in names:
        s8 = float(s8)
        S8 = s8 * np.sqrt(Om / 0.3)
        g = g_om * (s8 / (2.0 * np.sqrt(0.3 * Om)))
        g[names.index("sigma8")] += np.sqrt(Om / 0.3)
        out["S8"] = {"fiducial": float(S8), "sigma": float(np.sqrt(g @ cov @ g))}
    return out


def _inline_files_for_remote(config: dict) -> dict:
    """n(z) tables and the SRD covariance as JSON payload (server paths do not exist on the node)."""
    import base64
    files = {}
    for section in ("sources", "lenses"):
        kw = (config.get(section) or {}).get("Nz_kwargs") or {}
        p = kw.get("input_file")
        if p and os.path.isfile(p):
            if "npy" in str(kw.get("format", "npy")) and p.endswith(".npy"):
                files[os.path.basename(p)] = {"kind": "npy_b64",
                                              "data": base64.b64encode(Path(p).read_bytes()).decode()}
            else:
                files[os.path.basename(p)] = {"kind": "ascii", "data": np.loadtxt(p).tolist()}
    p = (config.get("cov_options") or {}).get("SRD_cov_path")
    if p and os.path.isfile(p):
        size = os.path.getsize(p)
        if size > 6 * 1024 * 1024:
            raise ValueError(
                f"SRD covariance {p} is {size / 1e6:.1f} MB - too large to embed in a remote kernel "
                "call. Use cov_type gaus_internal/tjpcov for remote runs, or run this tool locally.")
        files[os.path.basename(p)] = {"kind": "npy_b64",
                                      "data": base64.b64encode(Path(p).read_bytes()).decode()}
    return files


def _run_forecast_kernel(config: dict, mode: str, env_setup: str | None, duration: int,
                         include_bias=None, max_cov_return: int = 600) -> tuple[dict, str]:
    """Run tools.inner.augur_forecast.main locally or on the active dispatch site."""
    from mcp_server.dispatch import remote_site, run_env_kernel  # lazy: server-only

    site = remote_site()
    params = {"config": copy.deepcopy(config), "mode": mode, "include_bias": include_bias,
              "max_cov_return": max_cov_return}
    if site:
        if not env_setup or not env_setup.strip():
            raise ValueError(
                f"Dispatch is set to {site}: this call needs env_setup, a shell snippet that "
                "activates a facility environment with augur + firecrown >= 1.14 (see "
                "export_dispatch_pack -> env_kernel.env_setup_candidates, e.g. the NERSC "
                "desc-python activation). Nothing is chosen by the server.")
        params["inline_files"] = _inline_files_for_remote(config)
        params["relocate_outputs"] = True
        res = run_env_kernel(env_setup, "augur_forecast", params, duration=duration)
        out = res["result"]["result"]
        out["_env_check"] = res["result"].get("env_check")
        out["_artifact_files"] = res.get("artifact_files")
        return out, str(res.get("host", site))
    from ..inner.augur_forecast import main as _main
    params["job_dir"] = os.path.dirname(os.path.abspath(str(config["fiducial_sacc_path"])))
    return _main(params), "local"


# ---------------------------------------------------------------------------
# validation (pure python, milliseconds)
# ---------------------------------------------------------------------------
def _srd_layout_check(cfg: dict, year: str) -> list[str]:
    """Why a config does NOT match the SRD covariance layout for `year` ('' if it does)."""
    preset = SRD_PRESETS[year]
    problems = []
    ns = (cfg.get("sources") or {}).get("nbins")
    nl = (cfg.get("lenses") or {}).get("nbins")
    if ns != preset["n_source_bins"] or nl != preset["n_lens_bins"]:
        problems.append(f"SRD {year} covariance needs {preset['n_source_bins']} source + "
                        f"{preset['n_lens_bins']} lens bins, config has {ns} + {nl}")
    stats = cfg.get("statistics") or {}
    want = {"galaxy_shear_cl_ee": _pairs_all(5, 5, True),
            "galaxy_shearDensity_cl_e": preset["ggl_pairs"],
            "galaxy_density_cl": [[i, i] for i in range(preset["n_lens_bins"])]}
    for key, pairs in want.items():
        if key not in stats:
            problems.append(f"SRD covariance needs statistic {key} (all three 3x2pt statistics)")
            continue
        got = [list(p) for p in stats[key].get("tracer_combs", [])]
        if sorted(got) != sorted([list(p) for p in pairs]):
            problems.append(f"{key}.tracer_combs differ from the SRD {year} pair list ({len(pairs)} pairs)")
        try:
            edges = _parse_edges(stats[key].get("ell_edges"))
            if len(edges) - 1 != 20:
                problems.append(f"{key}: SRD covariance has 20 ell bands, config has {len(edges) - 1}")
        except Exception as exc:  # noqa: BLE001
            problems.append(f"{key}.ell_edges unparsable: {exc}")
    return problems


def _validate(cfg: dict) -> tuple[list[str], list[str], dict]:
    errors: list[str] = []
    warnings: list[str] = []
    info: dict = {}

    for key in ("cosmo", "statistics", "cov_options", "fiducial_sacc_path"):
        if key not in cfg:
            errors.append(f"missing top-level key '{key}'")
    if "general" not in cfg:
        warnings.append("no 'general' section: defaults ignore_scale_cuts=False, "
                        "ignore_scale_cuts_likelihood=False")
    cosmo = cfg.get("cosmo") or {}
    has_s8 = cosmo.get("sigma8") is not None
    has_as = cosmo.get("A_s") is not None
    if has_s8 == has_as:
        errors.append("cosmo must give exactly one of sigma8 / A_s")
    tf = str(cosmo.get("transfer_function", "boltzmann_camb")).lower()
    if tf == "boltzmann_isitgr":
        warnings.append("transfer_function boltzmann_isitgr (MG) is outside augur's registry and "
                        "falls back to CAMB settings; only mu_Sigma MG configs use it")
    elif tf not in TRANSFER_REGISTRY:
        errors.append(f"cosmo.transfer_function {tf!r} not in augur registry {TRANSFER_REGISTRY}")
    if tf in ("eisenstein_hu", "eh", "bbks") and has_as:
        errors.append(f"transfer_function {tf} cannot use A_s (analytic transfer functions need sigma8)")
    if tf == "boltzmann_camb":
        hv = ((cosmo.get("extra_parameters") or {}).get("camb") or {}).get("halofit_version")
        if not hv and str(cosmo.get("matter_power_spectrum", "halofit")).lower() != "linear":
            errors.append("transfer_function boltzmann_camb requires cosmo.extra_parameters.camb."
                          "halofit_version (e.g. takahashi, mead2020_feedback)")
    mps = str(cosmo.get("matter_power_spectrum", "halofit")).lower()
    if mps not in ("halofit", "linear", "camb"):
        errors.append(f"cosmo.matter_power_spectrum {mps!r}: augur supports halofit, linear (or camb with CAMB)")

    gen = cfg.get("general") or {}
    ign = bool(gen.get("ignore_scale_cuts", False))
    ign_lk = bool(gen.get("ignore_scale_cuts_likelihood", False))
    if (not ign) and ign_lk:
        errors.append("general: ignore_scale_cuts=False with ignore_scale_cuts_likelihood=True raises in augur")
    if ign_lk and "Firecrown_Factory" in cfg:
        errors.append("general.ignore_scale_cuts_likelihood=True with a Firecrown_Factory makes augur fall "
                      "back to a bare ConstGaussian likelihood WITHOUT systematics; set it to False")
    if str(gen.get("bandpower_windows", "None")) == "NaMaster":
        errors.append("general.bandpower_windows NaMaster is not implemented in augur")
    if "Firecrown_Factory" not in cfg:
        warnings.append("no Firecrown_Factory: augur uses the legacy ConstGaussian path with no "
                        "systematics (no IA, delta_z, m, galaxy bias updates)")
    else:
        if len(cfg["Firecrown_Factory"]) != 1 or "TwoPointFactory" not in cfg["Firecrown_Factory"]:
            errors.append("Firecrown_Factory must contain exactly one key: TwoPointFactory")

    # tracers
    nbins = {}
    for section, kind in (("sources", "src"), ("lenses", "lens")):
        blk = cfg.get(section)
        if not blk:
            continue
        n = blk.get("nbins")
        if not isinstance(n, int) or n < 1:
            errors.append(f"{section}.nbins must be a positive integer")
            continue
        nbins[kind] = n
        nd = blk.get("ndens")
        if nd is None or (isinstance(nd, (int, float)) and nd <= 0):
            errors.append(f"{section}.ndens must be > 0 [arcmin^-2]")
        if isinstance(nd, list) and len(nd) != n:
            errors.append(f"{section}.ndens list length {len(nd)} != nbins {n}")
        if section == "sources" and blk.get("ellipticity_error") is None:
            errors.append("sources.ellipticity_error (sigma_e) is required for the noise power")
        nz_type = blk.get("Nz_type")
        types = nz_type if isinstance(nz_type, list) else [nz_type]
        for t in types:
            if t not in NZ_REGISTRY:
                errors.append(f"{section}.Nz_type {t!r} not in augur registry {NZ_REGISTRY} "
                              "(TopHat/Gaussian are documented but unregistered)")
        kw = blk.get("Nz_kwargs") or {}
        if "ZDistFromFile" in types:
            p = kw.get("input_file")
            if not p:
                errors.append(f"{section}: ZDistFromFile needs Nz_kwargs.input_file")
            else:
                if "{{" in str(p):
                    errors.append(f"{section}.Nz_kwargs.input_file still contains a Jinja tag: {p}")
                elif not os.path.isabs(str(p)):
                    warnings.append(f"{section}.Nz_kwargs.input_file is relative ({p}); augur resolves it "
                                    "against the process cwd")
                if not os.path.isfile(str(p)):
                    errors.append(f"{section}: n(z) file not found: {p}")
                elif "ascii" in str(kw.get("format", "npy")):
                    try:
                        ncol = np.loadtxt(str(p), max_rows=2).shape[1]
                        if ncol < n + 1:
                            errors.append(f"{section}: {p} has {ncol - 1} n(z) columns < nbins {n}")
                    except Exception as exc:  # noqa: BLE001
                        errors.append(f"{section}: cannot read {p}: {exc}")
        if "LensSRD2018" in types:
            c = kw.get("Nz_center")
            try:
                nc = len(_parse_edges(c)) if c is not None else 0
            except Exception:  # noqa: BLE001
                nc = -1
            if nc != n:
                errors.append(f"{section}: LensSRD2018 Nz_center has {nc} entries, nbins is {n}")
            for need in ("Nz_width", "Nz_sigmaz"):
                if need not in kw:
                    errors.append(f"{section}: LensSRD2018 needs Nz_kwargs.{need}")
        if "SourceSRD2018" in types and "Nz_sigmaz" not in kw:
            errors.append(f"{section}: SourceSRD2018 needs Nz_kwargs.Nz_sigmaz")

    # statistics
    stats = cfg.get("statistics") or {}
    n_data = 0
    edges_seen = []
    for key, scfg in stats.items():
        if key not in DATA_TYPES:
            errors.append(f"statistics.{key}: unknown data type (augur generates "
                          f"{sorted(DATA_TYPES)} only; real-space statistics are not available)")
            continue
        if not isinstance(scfg, dict):
            errors.append(f"statistics.{key} must be a mapping")
            continue
        k1, k2 = DATA_TYPES[key]
        combs = scfg.get("tracer_combs") or []
        if not combs:
            errors.append(f"statistics.{key}.tracer_combs is empty")
        for comb in combs:
            if len(comb) != 2:
                errors.append(f"statistics.{key}: tracer comb {comb} must have two indices")
                continue
            for idx, kind in zip(comb, (k1, k2)):
                if kind not in nbins:
                    errors.append(f"statistics.{key} needs a '{'sources' if kind == 'src' else 'lenses'}' section")
                elif not (0 <= int(idx) < nbins[kind]):
                    errors.append(f"statistics.{key}: {kind}{idx} out of range (nbins={nbins[kind]})")
        if "kmax" in scfg and "lmax" in scfg:
            errors.append(f"statistics.{key}: give kmax [Mpc^-1] OR lmax, not both keys (augur raises "
                          "even when one of them is None)")
        km = scfg.get("kmax")
        if isinstance(km, (int, float)) and not isinstance(km, bool) and km > 1.0:
            warnings.append(f"statistics.{key}.kmax={km} Mpc^-1 is very nonlinear (SRD uses ~0.2)")
        try:
            edges = _parse_edges(scfg.get("ell_edges"))
            if len(edges) < 2 or np.any(np.diff(edges) <= 0):
                errors.append(f"statistics.{key}.ell_edges must be increasing with >= 2 values")
            n_data += len(combs) * (len(edges) - 1)
            edges_seen.append(edges)
        except Exception as exc:  # noqa: BLE001
            errors.append(f"statistics.{key}.ell_edges unparsable: {exc}")
    if len(edges_seen) > 1 and any(e.shape != edges_seen[0].shape or not np.allclose(e, edges_seen[0])
                                   for e in edges_seen[1:]):
        msg = "ell_edges differ between statistics"
        if (cfg.get("cov_options") or {}).get("cov_type") == "gaus_internal":
            errors.append(msg + " - gaus_internal assumes identical edges for all probes")
        else:
            warnings.append(msg)
    info["n_data_before_cuts"] = n_data

    # covariance
    cov = cfg.get("cov_options") or {}
    ct = cov.get("cov_type")
    if ct not in ("gaus_internal", "SRD", "tjpcov"):
        errors.append(f"cov_options.cov_type {ct!r} must be gaus_internal, SRD or tjpcov "
                      "(anything else silently yields an identity covariance)")
    if ct in ("gaus_internal", "tjpcov"):
        fs = cov.get("fsky")
        if not isinstance(fs, (int, float)) or not (0 < fs <= 1):
            errors.append("cov_options.fsky must be in (0, 1]")
    if ct == "SRD":
        p = cov.get("SRD_cov_path")
        if not p:
            errors.append("cov_type SRD needs cov_options.SRD_cov_path")
        else:
            if "{{" in str(p):
                errors.append(f"SRD_cov_path still contains a Jinja tag: {p}")
            elif not os.path.isfile(str(p)):
                errors.append(f"SRD covariance file not found: {p}")
            year = "Y10" if "Y10" in str(p) else "Y1"
            info["srd_year_from_path"] = year
            errors += _srd_layout_check(cfg, year)
    if ct == "tjpcov":
        te = (cov.get("binning_info") or {}).get("ell_edges")
        if te is None:
            errors.append("cov_type tjpcov needs cov_options.binning_info.ell_edges equal to the statistics' edges")
        elif edges_seen:
            try:
                tedges = _parse_edges(te)
                if tedges.shape != edges_seen[0].shape or not np.allclose(tedges, edges_seen[0]):
                    errors.append("cov_options.binning_info.ell_edges must equal statistics.*.ell_edges exactly")
            except Exception as exc:  # noqa: BLE001
                errors.append(f"cov_options.binning_info.ell_edges unparsable: {exc}")
    sp = cfg.get("fiducial_sacc_path")
    if sp and not os.path.isabs(str(sp)):
        warnings.append(f"fiducial_sacc_path is relative ({sp}); written relative to the process cwd")

    # fisher
    fisher = cfg.get("fisher")
    if fisher:
        sys_keys = set((cfg.get("systematics") or {}).keys())
        known = set(COSMO_KEYS) | sys_keys
        if "var_pars" in fisher:
            var_pars = list(fisher["var_pars"])
        elif "parameters" in fisher:
            var_pars = list(fisher["parameters"].keys())
            if "postprocess" in cfg:
                warnings.append("fisher.parameters mode + postprocess: augur's postprocess reads "
                                "fisher.var_pars and will KeyError")
        else:
            var_pars = []
            errors.append("fisher needs var_pars (list) or parameters (name: [min, fid, max])")
        if len(set(var_pars)) != len(var_pars):
            errors.append("fisher.var_pars has duplicates")
        for v in var_pars:
            if v not in known:
                errors.append(f"var_pars entry {v!r} is neither a CCL cosmology key nor in systematics")
        if "sigma8" in var_pars and "A_s" in var_pars:
            errors.append("var_pars lists both sigma8 and A_s")
        if "sigma8" in var_pars and not has_s8:
            errors.append("sigma8 in var_pars but the fiducial cosmology uses A_s")
        if "A_s" in var_pars and not has_as:
            errors.append("A_s in var_pars but the fiducial cosmology uses sigma8")
        t_om = bool(fisher.get("transform_Omega_m", False))
        t_s8 = bool(fisher.get("transform_S8", False))
        if t_om and "Omega_c" not in var_pars:
            errors.append("transform_Omega_m requires Omega_c in var_pars")
        if t_s8 and "sigma8" not in var_pars:
            errors.append("transform_S8 requires sigma8 in var_pars")
        priors = fisher.get("gaussian_priors") or {}
        bad = [p for p in priors if not (p in var_pars or (p == "Omega_m" and t_om) or (p == "S8" and t_s8))]
        if bad:
            errors.append(f"gaussian_priors for parameters not in var_pars (augur raises ValueError): "
                          f"{bad} - remove them or add them to var_pars")
        if t_om and "Omega_m" in priors and "Omega_c" in priors:
            errors.append("priors on both Omega_c and Omega_m")
        if t_s8 and "S8" in priors and "sigma8" in priors:
            errors.append("priors on both sigma8 and S8")
        for p, s in priors.items():
            if not isinstance(s, (int, float)) or s <= 0:
                errors.append(f"gaussian_priors.{p} must be a positive width")
        step = fisher.get("step", 0.01)
        try:
            step = float(step)
            if step <= 0:
                errors.append("fisher.step must be > 0")
            elif step < 1e-4:
                warnings.append(f"fisher.step={step:g} is ABSOLUTE and tiny: with CCL splines the "
                                "derivatives can be noise dominated (1e-3..1e-2 is safer)")
            elif step >= 0.1:
                warnings.append(f"fisher.step={step:g} is large for parameters like Omega_b or delta_z")
        except (TypeError, ValueError):
            errors.append("fisher.step must be numeric")
        method = fisher.get("derivative_method", "numdifftools")
        if method not in ("numdifftools", "5pt_stencil", "derivkit"):
            errors.append(f"fisher.derivative_method {method!r} not in numdifftools/5pt_stencil/derivkit")
        for key in ("output", "fid_output"):
            p = fisher.get(key)
            if not p:
                errors.append(f"fisher.{key} is required (augur writes text outputs there)")
            elif not os.path.isabs(str(p)):
                warnings.append(f"fisher.{key} is relative ({p}); augur writes it relative to the cwd")
        fb = fisher.get("fisher_bias")
        if fb:
            if t_om or t_s8:
                errors.append("fisher_bias cannot be combined with transform_S8/transform_Omega_m")
            bp = fb.get("bias_params") or {}
            bdv = fb.get("biased_dv") or ""
            if not bp and not (bdv and os.path.isfile(str(bdv))):
                errors.append("fisher_bias needs bias_params or an existing biased_dv file")
            for p in bp:
                if p not in known:
                    errors.append(f"fisher_bias.bias_params.{p} is not a cosmology or systematics parameter")
        n = len(var_pars)
        evals = {"numdifftools": 2 * n + 1, "5pt_stencil": 4 * n + 1, "derivkit": 27 * n}.get(method, 2 * n + 1)
        info.update({"n_var_pars": n, "var_pars": var_pars, "n_priors_applied": len(priors) - len(bad),
                     "estimated_likelihood_evaluations": evals + 1 + (2 if fb else 0),
                     "derivative_method": method, "step": step})
    return errors, warnings, info


# ---------------------------------------------------------------------------
# tools
# ---------------------------------------------------------------------------
@validate_call
def augur_list_examples() -> ArtifactResult:
    """List augur's shipped example forecast configs, SRD data files and parameter conventions.

    Reads (read-only) the augur clone's examples/*.yml and data/ (DESC_AUGUR_DIR
    or the sibling checkout). For each example: survey year, probes, bin
    layout, number densities, covariance type, transfer function, varied
    parameters, step, priors, and whether it would run as shipped (the
    validator verdict - the SRD examples list priors for parameters they do
    not vary and are 'no-go' until trimmed, which augur_generate_forecast_config
    does automatically). Use it to pick a starting point; then call
    augur_generate_forecast_config rather than copying a YAML (the examples
    use Jinja {{ env['AUGUR_DIR'] }} paths).
    """
    clone = clone_dir("augur")
    examples: dict = {}
    data_files: dict = {}
    if clone is not None:
        for path in sorted((clone / "examples").glob("*.yml")) + sorted((clone / "augur" / "tests").glob("test.yaml")):
            try:
                cfg = _render_yaml_text(path)
                errors, warns, info = _validate(cfg)
                stats = cfg.get("statistics") or {}
                fisher = cfg.get("fisher") or {}
                vp = fisher.get("var_pars") or list((fisher.get("parameters") or {}).keys())
                priors = fisher.get("gaussian_priors") or {}
                examples[path.name] = {
                    "path": str(path),
                    "survey_year": "Y10" if "y10" in path.name.lower() else ("Y1" if "y1" in path.name.lower() else "custom"),
                    "probes": sorted(stats.keys()),
                    "n_source_bins": (cfg.get("sources") or {}).get("nbins"),
                    "n_lens_bins": (cfg.get("lenses") or {}).get("nbins"),
                    "ndens_source_arcmin2": (cfg.get("sources") or {}).get("ndens"),
                    "ndens_lens_arcmin2": (cfg.get("lenses") or {}).get("ndens"),
                    "nz_type": {"sources": (cfg.get("sources") or {}).get("Nz_type"),
                                "lenses": (cfg.get("lenses") or {}).get("Nz_type")},
                    "cov_type": (cfg.get("cov_options") or {}).get("cov_type"),
                    "transfer_function": (cfg.get("cosmo") or {}).get("transfer_function", "boltzmann_camb"),
                    "n_var_pars": len(vp), "var_pars": vp,
                    "step": fisher.get("step"), "derivative_method": fisher.get("derivative_method"),
                    "n_gaussian_priors": len(priors),
                    "priors_not_in_var_pars": [p for p in priors if p not in vp],
                    "has_fisher_bias": "fisher_bias" in fisher,
                    "has_mg": "mg_parametrization" in (cfg.get("cosmo") or {}),
                    "runs_as_shipped": not errors,
                    "validator_errors": errors[:6],
                    "n_data_before_cuts": info.get("n_data_before_cuts"),
                }
            except Exception as exc:  # noqa: BLE001
                examples[path.name] = {"path": str(path), "error": f"{type(exc).__name__}: {exc}"}
        for path in sorted((clone / "data").glob("*")):
            entry = {"path": str(path), "bytes": path.stat().st_size}
            try:
                if path.suffix == ".txt":
                    arr = np.loadtxt(path)
                    entry.update({"shape": list(arr.shape), "format": "ascii: column 0 = z, columns 1.. = n(z) per bin",
                                  "z_range": [float(arr[0, 0]), float(arr[-1, 0])], "n_bins": int(arr.shape[1] - 1)})
                elif "cov" in path.name:
                    arr = np.load(path, mmap_mode="r")
                    entry.update({"shape": list(arr.shape),
                                  "format": "SRD v1 3x2pt covariance, 20 ells per tracer-pair block, "
                                            "fixed pair order (see CAVEATS)"})
                else:
                    entry["format"] = "npy dict {redshift_range, bins}"
            except Exception as exc:  # noqa: BLE001
                entry["error"] = str(exc)
            data_files[path.name] = entry
    message = (f"{len(examples)} example configs and {len(data_files)} data files in the augur clone."
               if clone is not None else
               "augur clone not available (set DESC_AUGUR_DIR); conventions and presets only.")
    return ArtifactResult(
        status="success", files=[], message=message,
        metadata={"augur_clone": str(clone) if clone else None, "examples": examples,
                  "data_files": data_files, "srd_presets": SRD_PRESETS,
                  "conventions": CONVENTIONS, "caveats": CAVEATS,
                  "next": "augur_generate_forecast_config(survey_year=..., probes=...)"})


@validate_call
def augur_generate_forecast_config(
    output_dir: Annotated[str, Field(min_length=1)],
    survey_year: Annotated[Literal["Y1", "Y10"], Field(description="LSST SRD year: sets bins (5/5 vs 5/10), ndens (10/18 vs 27/48 arcmin^-2), kmax, lens biases, n(z) files, SRD covariance.")] = "Y1",
    probes: Annotated[Literal["3x2pt", "shear", "clustering", "ggl"], Field(description="shear = cosmic shear only (sources), clustering = lens auto-spectra, ggl = galaxy-galaxy lensing, 3x2pt = all three.")] = "3x2pt",
    n_source_bins: Annotated[int | None, Field(ge=1, le=10, description="Source tomographic bins; None = SRD (5). nz_mode='file' allows at most 5.")] = None,
    n_lens_bins: Annotated[int | None, Field(ge=1, le=12, description="Lens bins; None = SRD (Y1: 5, Y10: 10). nz_mode='file' allows at most 5 (Y1) / 10 (Y10).")] = None,
    ndens_source: Annotated[float | None, Field(gt=0, le=100, description="Total source density [arcmin^-2]; None = SRD (Y1 10, Y10 27).")] = None,
    ndens_lens: Annotated[float | None, Field(gt=0, le=200, description="Total lens density [arcmin^-2]; None = SRD (Y1 18, Y10 48).")] = None,
    sigma_e: Annotated[float, Field(gt=0, le=1, description="Per-component shape noise.")] = 0.26,
    ell_min: Annotated[float, Field(ge=2, le=1000)] = 20.0,
    ell_max: Annotated[float, Field(ge=50, le=30000)] = 15000.0,
    n_ell: Annotated[int, Field(ge=3, le=100, description="Number of log-spaced ell bands (SRD: 20).")] = 20,
    kmax: Annotated[float | None, Field(gt=0, le=5, description="Scale cut for probes with lenses [Mpc^-1, NO h]; converted to lmax = kmax*chi(z_mean). None = SRD (0.202 / 0.201). Ignored when lmax is given.")] = None,
    lmax: Annotated[float | None, Field(ge=10, le=30000, description="Alternative to kmax: a fixed multipole cut for lens probes.")] = None,
    shear_lmax: Annotated[float | None, Field(ge=10, le=30000, description="Optional multipole cut for cosmic shear (SRD applies none).")] = None,
    cov_type: Annotated[Literal["gaus_internal", "SRD", "tjpcov"], Field(description="gaus_internal = augur's mode-counting Gaussian (any layout, fast); SRD = the DESC SRD v1 covariance (requires the exact SRD layout, 3x2pt only); tjpcov = TJPCov Gaussian f_sky (slow).")] = "gaus_internal",
    fsky: Annotated[float | None, Field(gt=0, le=1, description="Sky fraction for gaus_internal/tjpcov; None = SRD-like (Y1 0.3, Y10 0.4).")] = None,
    cosmology: Annotated[CosmologyParams | None, Field(description="Fiducial cosmology; None = DESC SRD values with eisenstein_hu + halofit (fast). boltzmann_camb gets halofit_version=takahashi automatically.")] = None,
    var_pars: Annotated[list[str] | None, Field(description="Parameters to vary (firecrown names). None = SRD set: Omega_c, sigma8, n_s, w0, wa, Omega_b, h, lens0_bias, lens1_bias (lens biases only when lenses exist).")] = None,
    step: Annotated[float, Field(gt=0, le=0.5, description="ABSOLUTE finite-difference step in parameter units.")] = 0.01,
    derivative_method: Annotated[Literal["numdifftools", "5pt_stencil", "derivkit"], Field(description="numdifftools: 2n+1 evaluations; 5pt_stencil: 4n+1; derivkit: ~27n (adaptive).")] = "numdifftools",
    gaussian_priors: Annotated[dict[str, float] | None, Field(description="{param: 1-sigma width}; every key must be in var_pars (checked here).")] = None,
    srd_priors: Annotated[bool, Field(description="Add the SRD prior widths (Omega_c 0.2, Omega_b 0.006, h 0.063, n_s 0.08, sigma8 0.14, w0 0.8, wa 2.0, biases 0.9, delta_z 0.002/0.005, m 0.013, IA 3.9/2.3) for the parameters that ARE varied.")] = False,
    fisher_bias_params: Annotated[dict[str, float] | None, Field(description="Optional Fisher-bias probe: {param: shifted value} evaluated as a 'wrong' data vector (e.g. {'Omega_c': 0.27}).")] = None,
    transform_S8: Annotated[bool, Field(description="Report the Fisher matrix in S8 instead of sigma8 (needs sigma8 in var_pars).")] = False,
    transform_Omega_m: Annotated[bool, Field(description="Report in Omega_m instead of Omega_c (needs Omega_c in var_pars).")] = False,
    nz_mode: Annotated[Literal["file", "analytic"], Field(description="file = the SRD n(z) tables shipped with augur (ZDistFromFile); analytic = SourceSRD2018/LensSRD2018 parametric n(z) (any bin count).")] = "file",
    lens_bias: Annotated[list[float] | None, Field(description="Fiducial linear bias per lens bin; None = SRD values (or 1.0 + 0.1 i beyond the SRD count).")] = None,
    ggl_pairs: Annotated[list[list[int]] | None, Field(description="[lens_i, src_j] pairs for galaxy-galaxy lensing; None = SRD list when the layout matches, else all pairs.")] = None,
    label: Annotated[str | None, Field(description="Short tag for file names.")] = None,
) -> ArtifactResult:
    """Write a complete, Jinja-free augur forecast YAML (absolute paths) for an LSST Y1/Y10 forecast.

    Encodes the DESC SRD setups exactly like augur/examples/srd_y1_3x2.yml and
    srd_y10_3x2.yml (eisenstein_hu + halofit, SRD n(z) tables, lens biases, IA
    fiducials, 20 log-spaced ell bands 20..15000, kmax 0.2 Mpc^-1 on lens
    probes, general.ignore_scale_cuts=True with likelihood-side cuts) but
    with every path absolute and the prior list trimmed to var_pars, so the
    result validates and runs as written. Units: ndens arcmin^-2, kmax Mpc^-1
    (no h), ell dimensionless, step ABSOLUTE. Outputs: <output_dir>/augur_<label>_<slug>/
    forecast_config.yml + forecast_config.json (echo), with the sacc and augur
    text outputs destined for the same directory. Metadata reports the
    expected data-vector size, the evaluation count (2n+1 for numdifftools)
    and whether the SRD covariance layout matches. Next: augur_validate_forecast_config,
    then augur_generate_synthetic_datavector / augur_compute_fisher.
    """
    preset = SRD_PRESETS[survey_year]
    data_dir = _augur_data_dir()
    use_src = probes in ("3x2pt", "shear", "ggl")
    use_lens = probes in ("3x2pt", "clustering", "ggl")
    ns = n_source_bins if n_source_bins is not None else preset["n_source_bins"]
    nl = n_lens_bins if n_lens_bins is not None else preset["n_lens_bins"]
    nd_s = ndens_source if ndens_source is not None else preset["ndens_source"]
    nd_l = ndens_lens if ndens_lens is not None else preset["ndens_lens"]
    kmax_v = kmax if kmax is not None else preset["kmax"]
    fsky_v = fsky if fsky is not None else preset["fsky"]
    spec = cosmology or CosmologyParams(preset="desc_srd", transfer_function="eisenstein_hu")

    if nz_mode == "file":
        src_cols = 5
        lens_cols = preset["n_lens_bins"]
        if use_src and ns > src_cols:
            raise ValueError(f"nz_mode='file': the SRD {survey_year} source table has {src_cols} bins; "
                             f"use nz_mode='analytic' for {ns} bins")
        if use_lens and nl > lens_cols:
            raise ValueError(f"nz_mode='file': the SRD {survey_year} lens table has {lens_cols} bins; "
                             f"use nz_mode='analytic' for {nl} bins")
    # cosmology -> augur cosmo block
    if spec.baryons != "none":
        raise ValueError("augur ignores baryonic_effects; set cosmology.baryons='none'")
    if spec.mg_mu0 or spec.mg_sigma0:
        raise ValueError("mu-Sigma MG forecasts are not generated here: start from "
                         "augur/examples/srd_y1_3x2_mg.yml by hand")
    if spec.matter_power_spectrum not in ("halofit", "linear", "camb_hmcode"):
        raise ValueError(f"augur supports matter_power_spectrum halofit/linear/camb_hmcode, "
                         f"not {spec.matter_power_spectrum}")
    if spec.transfer_function == "eisenstein_hu_nowiggles":
        raise ValueError("augur's transfer-function registry has no eisenstein_hu_nowiggles; use eisenstein_hu")
    cosmo_block = dict(spec.firecrown_params())
    cosmo_block["mass_split"] = spec.mass_split
    cosmo_block["transfer_function"] = spec.transfer_function
    if spec.matter_power_spectrum == "camb_hmcode":
        if spec.transfer_function != "boltzmann_camb":
            raise ValueError("camb_hmcode needs transfer_function='boltzmann_camb'")
        cosmo_block["matter_power_spectrum"] = "camb"
        cosmo_block["extra_parameters"] = {"camb": {"halofit_version": "mead2020_feedback",
                                                     "HMCode_logT_AGN": spec.hmcode_logT_AGN,
                                                     "kmax": 20.0}}
    else:
        cosmo_block["matter_power_spectrum"] = spec.matter_power_spectrum
        if spec.transfer_function == "boltzmann_camb":
            cosmo_block["extra_parameters"] = {"camb": {"halofit_version": "takahashi",
                                                         "dark_energy_model": "ppf"}}
    # systematics block
    systematics: dict[str, float] = {}
    if use_src:
        for i in range(ns):
            systematics[f"src{i}_mult_bias"] = 0.0
            systematics[f"src{i}_delta_z"] = 0.0
        systematics.update(IA_FIDUCIAL)
    biases = []
    if use_lens:
        base = list(preset["lens_bias"])
        if lens_bias is not None:
            if len(lens_bias) != nl:
                raise ValueError(f"lens_bias has {len(lens_bias)} entries, n_lens_bins is {nl}")
            biases = [float(b) for b in lens_bias]
        else:
            biases = [base[i] if i < len(base) else round(1.0 + 0.1 * i, 3) for i in range(nl)]
        for i in range(nl):
            systematics[f"lens{i}_bias"] = biases[i]
            systematics[f"lens{i}_alphaz"] = 0.0
            systematics[f"lens{i}_z_piv"] = 0.0
            systematics[f"lens{i}_alphag"] = 0.0
            systematics[f"lens{i}_delta_z"] = 0.0
            systematics[f"lens{i}_sigma_z"] = 1.0
    # var_pars + priors
    if var_pars is None:
        var_pars = ["Omega_c", "sigma8", "n_s", "w0", "wa", "Omega_b", "h"]
        if spec.sigma8 is None:
            var_pars[1] = "A_s"
        if use_lens:
            var_pars += [f"lens{i}_bias" for i in range(min(2, nl))]
    known = set(COSMO_KEYS) | set(systematics)
    unknown = [p for p in var_pars if p not in known]
    if unknown:
        raise ValueError(f"var_pars not in the cosmology or systematics of this setup: {unknown}. "
                         f"Available nuisance parameters: {sorted(systematics)}")
    if "sigma8" in var_pars and spec.sigma8 is None:
        raise ValueError("sigma8 in var_pars but the cosmology is specified with A_s")
    if "A_s" in var_pars and spec.A_s is None:
        raise ValueError("A_s in var_pars but the cosmology is specified with sigma8")
    priors: dict[str, float] = {}
    if srd_priors:
        for p in var_pars:
            if p in SRD_PRIOR_WIDTHS:
                priors[p] = SRD_PRIOR_WIDTHS[p]
            elif p.endswith("_mult_bias"):
                priors[p] = SRD_PRIOR_PATTERNS["_mult_bias"]
            elif p.endswith("_delta_z"):
                priors[p] = SRD_PRIOR_PATTERNS["lens_delta_z" if p.startswith("lens") else "src_delta_z"]
            elif p.endswith("_bias"):
                priors[p] = SRD_PRIOR_PATTERNS["_bias"]
    if gaussian_priors:
        bad = [p for p in gaussian_priors
               if not (p in var_pars or (p == "Omega_m" and transform_Omega_m) or (p == "S8" and transform_S8))]
        if bad:
            raise ValueError(f"gaussian_priors for parameters not in var_pars: {bad} (augur would raise)")
        priors.update({k: float(v) for k, v in gaussian_priors.items()})
    if transform_Omega_m and "Omega_c" not in var_pars:
        raise ValueError("transform_Omega_m needs Omega_c in var_pars")
    if transform_S8 and "sigma8" not in var_pars:
        raise ValueError("transform_S8 needs sigma8 in var_pars")
    if fisher_bias_params:
        if transform_S8 or transform_Omega_m:
            raise ValueError("Fisher bias cannot be combined with the S8/Omega_m transforms (augur refuses)")
        bad = [p for p in fisher_bias_params if p not in known]
        if bad:
            raise ValueError(f"fisher_bias_params not in the model: {bad}")

    # tracers
    sources = lenses = None
    if use_src:
        if nz_mode == "file":
            nz_kw = {"input_file": str(data_dir / preset["nz_source_file"]), "format": "ascii"}
            nz_type = "ZDistFromFile"
        else:
            nz_kw = dict(preset["source_nz"])
            nz_type = "SourceSRD2018"
        sources = {"nbins": ns, "ndens": float(nd_s), "ellipticity_error": float(sigma_e),
                   "Nz_type": nz_type, "Nz_kwargs": nz_kw}
    if use_lens:
        if nz_mode == "file":
            nz_kw = {"input_file": str(data_dir / preset["nz_lens_file"]), "format": "ascii"}
            nz_type = "ZDistFromFile"
        else:
            lp = dict(preset["lens_nz"])
            centers = list(lp.pop("Nz_center"))
            width = lp["Nz_width"]
            if nl != len(centers):  # re-slice 0.2..1.2 into nl bins of equal width
                width = round(1.0 / nl, 4)
                centers = [round(0.2 + width * (i + 0.5), 4) for i in range(nl)]
                lp["Nz_width"] = width
            nz_kw = {"Nz_center": centers, **lp}
            nz_type = "LensSRD2018"
        lenses = {"nbins": nl, "ndens": float(nd_l), "Nz_type": nz_type, "Nz_kwargs": nz_kw}

    # statistics
    edges_str = f"np.geomspace({ell_min:g}, {ell_max:g}, {n_ell + 1}, endpoint=True)"
    edges = np.geomspace(ell_min, ell_max, n_ell + 1)
    layout_is_srd = (ns == preset["n_source_bins"] and nl == preset["n_lens_bins"] and n_ell == 20
                     and abs(ell_min - 20) < 1e-9 and abs(ell_max - 15000) < 1e-9)
    statistics: dict = {}
    if probes in ("3x2pt", "shear"):
        statistics["galaxy_shear_cl_ee"] = {"tracer_combs": _pairs_all(ns, ns, True), "ell_edges": edges_str}
        if shear_lmax is not None:
            statistics["galaxy_shear_cl_ee"]["lmax"] = float(shear_lmax)
    lens_cut = {"lmax": float(lmax)} if lmax is not None else {"kmax": float(kmax_v)}
    if probes in ("3x2pt", "ggl"):
        if ggl_pairs is not None:
            pairs = [[int(a), int(b)] for a, b in ggl_pairs]
            for a, b in pairs:
                if not (0 <= a < nl and 0 <= b < ns):
                    raise ValueError(f"ggl pair [lens{a}, src{b}] out of range (lenses {nl}, sources {ns})")
        elif ns == preset["n_source_bins"] and nl == preset["n_lens_bins"]:
            pairs = [list(p) for p in preset["ggl_pairs"]]
        else:
            pairs = _pairs_all(nl, ns, False)
        statistics["galaxy_shearDensity_cl_e"] = {"tracer_combs": pairs, "ell_edges": edges_str, **lens_cut}
    if probes in ("3x2pt", "clustering"):
        statistics["galaxy_density_cl"] = {"tracer_combs": [[i, i] for i in range(nl)],
                                           "ell_edges": edges_str, **lens_cut}
    # covariance
    if cov_type == "SRD":
        cov_opts = {"cov_type": "SRD", "SRD_cov_path": str(data_dir / preset["srd_cov_file"])}
    elif cov_type == "tjpcov":
        cov_opts = {"cov_type": "tjpcov", "fsky": float(fsky_v), "IA": None,
                    "binning_info": {"ell_edges": edges_str}}
    else:
        cov_opts = {"cov_type": "gaus_internal", "fsky": float(fsky_v)}

    # paths
    tag = label or f"{survey_year}_{probes}"
    slug = param_slug({"year": survey_year, "probes": probes, "ns": ns, "nl": nl, "nd": (nd_s, nd_l),
                       "ell": (ell_min, ell_max, n_ell), "cut": (kmax_v, lmax, shear_lmax),
                       "cov": cov_type, "fsky": fsky_v, "cosmo": spec.slug(), "var": tuple(var_pars),
                       "step": step, "method": derivative_method, "priors": tuple(sorted(priors.items())),
                       "bias": tuple(sorted((fisher_bias_params or {}).items())), "nz": nz_mode,
                       "t": (transform_S8, transform_Omega_m), "sig": sigma_e})
    run_dir = resolve_outdir(output_dir) / f"augur_{tag}_{slug}"
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "augur_out").mkdir(exist_ok=True)

    config = {
        "fiducial_sacc_path": str(run_dir / "fiducial_datavector.sacc"),
        "general": {"ignore_scale_cuts": True, "ignore_scale_cuts_likelihood": False,
                    "bandpower_windows": "None"},
        "cosmo": cosmo_block,
        "ccl_accuracy": {"spline_params": {"K_MAX_SPLINE": 100}},
        "systematics": systematics,
        "Firecrown_Factory": copy.deepcopy(FIRECROWN_FACTORY),
    }
    if sources:
        config["sources"] = sources
    if lenses:
        config["lenses"] = lenses
    config["statistics"] = statistics
    config["cov_options"] = cov_opts
    fisher = {"var_pars": list(var_pars), "step": float(step), "derivative_method": derivative_method,
              "output": str(run_dir / "augur_out" / "fisher.dat"),
              "fid_output": str(run_dir / "augur_out" / "fiducials.dat")}
    if priors:
        fisher["gaussian_priors"] = priors
    if transform_S8:
        fisher["transform_S8"] = True
    if transform_Omega_m:
        fisher["transform_Omega_m"] = True
    if fisher_bias_params:
        fisher["fisher_bias"] = {"biased_dv": "", "bias_params": {k: float(v) for k, v in fisher_bias_params.items()}}
    config["fisher"] = fisher

    errors, warns, info = _validate(config)
    if errors:  # should not happen - surface loudly rather than write a broken file
        raise ValueError("generated config fails validation: " + "; ".join(errors))

    import yaml
    yml_path = run_dir / "forecast_config.yml"
    yml_path.write_text(
        f"# augur forecast config generated by desc-mcp-server ({survey_year} {probes}, {spec.label()})\n"
        "# Units: ndens arcmin^-2, kmax Mpc^-1 (no h), ells dimensionless, fisher.step ABSOLUTE.\n"
        + yaml.safe_dump(config, sort_keys=False, default_flow_style=None, width=100),
        encoding="utf-8")
    json_path = run_dir / "forecast_config.json"
    write_json(json_path, {"config": config, "survey_year": survey_year, "probes": probes,
                           "cosmology": spec.model_dump(), "label": tag})

    n_pairs = {k: len(v["tracer_combs"]) for k, v in statistics.items()}
    n_par = len(var_pars)
    evals = {"numdifftools": 2 * n_par + 1, "5pt_stencil": 4 * n_par + 1, "derivkit": 27 * n_par}[derivative_method]
    srd_cov_possible = layout_is_srd and probes == "3x2pt" and (
        ggl_pairs is None or sorted(map(list, ggl_pairs)) == sorted(map(list, preset["ggl_pairs"])))
    metadata = {
        "config_path": str(yml_path), "run_dir": str(run_dir), "survey_year": survey_year, "probes": probes,
        "n_source_bins": ns if use_src else 0, "n_lens_bins": nl if use_lens else 0,
        "ndens_arcmin2": {"source": nd_s if use_src else None, "lens": nd_l if use_lens else None},
        "ell_bands": {"n": n_ell, "edges": [round(float(e), 3) for e in edges]},
        "scale_cuts": {"lens_probes": lens_cut, "shear_lmax": shear_lmax, "kmax_units": "Mpc^-1 (no h)"},
        "n_pairs": n_pairs, "n_data_before_cuts": info.get("n_data_before_cuts"),
        "cov_type": cov_type, "fsky": fsky_v if cov_type != "SRD" else None,
        "srd_covariance_layout_match": srd_cov_possible,
        "cosmology": spec.model_dump(),
        "cosmology_label": spec.label(),
        "var_pars": list(var_pars), "gaussian_priors": priors, "step_absolute": step,
        "derivative_method": derivative_method,
        "estimated_likelihood_evaluations": evals + 1 + (2 if fisher_bias_params else 0),
        "fisher_bias_params": fisher_bias_params or None,
        "validator": {"errors": errors, "warnings": warns},
        "nuisance_parameters_available": sorted(systematics),
        "units": CONVENTIONS,
    }
    msg = (f"Wrote augur {survey_year} {probes} forecast config ({sum(n_pairs.values())} tracer pairs x "
           f"{n_ell} ells = {info.get('n_data_before_cuts')} data points before cuts; {n_par} varied "
           f"parameters -> ~{metadata['estimated_likelihood_evaluations']} likelihood evaluations; "
           f"cov {cov_type}).")
    if cov_type != "SRD" and srd_cov_possible:
        msg += " Layout matches the SRD covariance: cov_type='SRD' is available."
    return ArtifactResult(status="success", files=[str(yml_path), str(json_path)], message=msg, metadata=metadata)


@validate_call
def augur_validate_forecast_config(
    config_path: Annotated[str, Field(min_length=1, description="Path to an augur YAML (ours or a shipped example; Jinja AUGUR_DIR tags are rendered with the clone path).")],
) -> ArtifactResult:
    """Check an augur forecast YAML for the known traps before any (possibly remote) run; returns go/no-go.

    Pure-python, milliseconds. Errors (no-go): gaussian_priors keys not in
    var_pars (unless Omega_m/S8 with the transform), both or neither of
    sigma8/A_s, kmax AND lmax keys on one statistic, cov_type SRD without the
    exact SRD layout (5/5 or 5/10 bins, SRD pair lists, all three statistics,
    20 ells), ignore_scale_cuts_likelihood=True with a Firecrown_Factory
    (silently drops systematics), boltzmann_camb without
    extra_parameters.camb.halofit_version, Nz_type not in augur's registry,
    missing n(z)/covariance files, tracer indices out of range, unknown
    var_pars, bad step/method, fisher_bias + transforms. Warnings: relative
    paths, tiny/large ABSOLUTE steps, differing ell edges, legacy likelihood.
    Metadata also gives the data-vector size and the expected number of
    likelihood evaluations (cost estimate for dispatch).
    """
    cfg = _load_config(config_path)
    errors, warns, info = _validate(cfg)
    verdict = "go" if not errors else "no-go"
    return ArtifactResult(
        status="success", files=[],
        message=f"{verdict}: {len(errors)} errors, {len(warns)} warnings for {config_path}.",
        metadata={"verdict": verdict, "ok": not errors, "errors": errors, "warnings": warns, **info,
                  "config_path": str(Path(config_path).expanduser().resolve())})


def _plot_datavector(rows: list[dict], path: Path, title: str) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from ..plotting import LINESTYLES, PALETTE, rc_params

    stats = sorted({r["stat"] for r in rows})
    with plt.rc_context(rc_params(11)):
        fig, axes = plt.subplots(1, len(stats), figsize=(5.2 * len(stats), 4.2), constrained_layout=True,
                                 squeeze=False)
        for ax, stat in zip(axes[0], stats):
            pairs = sorted({(r["tr1"], r["tr2"]) for r in rows if r["stat"] == stat})
            for k, (t1, t2) in enumerate(pairs):
                sel = [r for r in rows if r["stat"] == stat and r["tr1"] == t1 and r["tr2"] == t2]
                ell = np.array([r["ell"] for r in sel])
                cl = np.array([r["cl"] for r in sel])
                sig = np.array([r["sigma"] or 0.0 for r in sel])
                keep = np.array([r["in_likelihood"] for r in sel])
                color = PALETTE[k % len(PALETTE)]
                ls = LINESTYLES[(k // len(PALETTE)) % len(LINESTYLES)]
                ax.errorbar(ell[keep], np.abs(cl[keep]), yerr=sig[keep], color=color, ls=ls, lw=1.2,
                            capsize=1.5, label=f"{t1}-{t2}" if len(pairs) <= 10 else None)
                if (~keep).any():
                    ax.plot(ell[~keep], np.abs(cl[~keep]), color=color, ls=":", lw=0.8, alpha=0.5)
            ax.set_xscale("log")
            ax.set_yscale("log")
            ax.set_xlabel(r"Multipole $\ell$")
            ax.set_ylabel(r"$|C_\ell|$")
            ax.set_title(f"{stat} ({len(pairs)} pairs)")
            if len(pairs) <= 10:
                ax.legend(ncol=2, fontsize=7)
        fig.suptitle(title, fontsize=11)
        fig.savefig(path, dpi=150)
        plt.close(fig)


@validate_call
def augur_generate_synthetic_datavector(
    output_dir: Annotated[str, Field(min_length=1)],
    config_path: Annotated[str, Field(min_length=1, description="Forecast YAML from augur_generate_forecast_config (validated).")],
    env_setup: Annotated[str | None, Field(description="Facility environment activation (only used when dispatch is remote), e.g. the NERSC desc-python snippet from export_dispatch_pack.")] = None,
    plot: Annotated[bool, Field(description="Write a PNG of all C_ell with error bars.")] = True,
    duration_s: Annotated[int, Field(ge=120, le=14400, description="Walltime for a remote job.")] = 900,
) -> ArtifactResult:
    """Run augur.generate: fiducial theory C_ell for every tracer pair + covariance -> sacc, CSV, n(z), PNG.

    One likelihood evaluation plus the covariance (gaus_internal: seconds;
    tjpcov: minutes, dispatchable). Writes <output_dir>/datavector_<slug>.csv
    with columns stat, tr1, tr2, ell, cl, sigma (sqrt of the covariance
    diagonal), in_likelihood (0/1: survives the scale cut applied in the
    likelihood; the sacc keeps all ells because general.ignore_scale_cuts=True),
    nz_sources/nz_lenses CSVs (z, nz per bin), cov.npy (full covariance when
    returned, always the diagonal), and a PNG. The sacc file goes to the
    config's fiducial_sacc_path (locally) or the job directory (remote).
    Metadata: total S/N = sqrt(d C^-1 d), per-statistic counts, lmax actually
    kept per pair (kmax converted with chi(z_mean)). Next: augur_compute_fisher.
    """
    cfg = _load_config(config_path)
    errors, warns, info = _validate(cfg)
    if errors:
        raise ValueError("config fails validation (run augur_validate_forecast_config): " + "; ".join(errors[:5]))
    out, computed_on = _run_forecast_kernel(cfg, "generate", env_setup, duration_s, max_cov_return=1200)

    outdir = resolve_outdir(output_dir)
    slug = param_slug({"cfg": str(Path(config_path).resolve()), "n": out["n_data"]})
    rows = out["data_vector"]
    label = f"augur synthetic data vector ({out['cov_type']}, {out['n_data']} points)"
    dv_path = outdir / f"datavector_{slug}.csv"
    _write_table(dv_path, [f"label: {label}", "quantity: angular_power_spectra",
                           "units: ell dimensionless, cl dimensionless, sigma = sqrt(diag cov)",
                           f"config: {config_path}", f"sacc: {out['sacc_path']}", f"cov_type: {out['cov_type']}"],
                 {"stat": [r["stat"] for r in rows], "tr1": [r["tr1"] for r in rows],
                  "tr2": [r["tr2"] for r in rows], "ell": [float(r["ell"]) for r in rows],
                  "cl": [float(r["cl"]) for r in rows],
                  "sigma": [float(r["sigma"]) if r["sigma"] is not None else float("nan") for r in rows],
                  "in_likelihood": [int(bool(r["in_likelihood"])) for r in rows]})
    files = [str(dv_path)]
    nz = out.get("nz") or {}
    for kind, fname in (("src", "nz_sources"), ("lens", "nz_lenses")):
        names = sorted([n for n in nz if n.startswith(kind)], key=lambda s: int(s[len(kind):]))
        if names:
            cols = {"z": np.asarray(nz[names[0]]["z"])}
            for n in names:
                cols[f"nz_{n}"] = np.asarray(nz[n]["nz"])
            p = outdir / f"{fname}_{slug}.csv"
            write_csv(p, cols, [f"label: {fname.replace('_', ' ')} n(z)", "quantity: nz",
                                "units: z dimensionless, nz arbitrary normalisation",
                                "zmean: " + ", ".join(f"{n}={nz[n]['zmean']:.3f}" for n in names)])
            files.append(str(p))
    cov = out.get("cov")
    cov_path = outdir / f"cov_{slug}.npy"
    if cov is not None:
        np.save(cov_path, np.asarray(cov, dtype=float))
    else:
        np.save(cov_path, np.asarray(out["cov_diag"], dtype=float))
    files.append(str(cov_path))
    if plot:
        png = outdir / f"datavector_{slug}.png"
        _plot_datavector(rows, png, label)
        files.append(str(png))
    sacc_local = out["sacc_path"] if computed_on == "local" and os.path.isfile(out["sacc_path"]) else None
    if sacc_local:
        files.append(sacc_local)

    snr = None
    if cov is not None:
        d = np.array([r["cl"] for r in rows])
        try:
            snr = float(np.sqrt(d @ np.linalg.solve(np.asarray(cov), d)))
        except np.linalg.LinAlgError:
            snr = None
    per_stat = {}
    for r in rows:
        per_stat.setdefault(r["stat"], {"n_points": 0, "n_in_likelihood": 0, "pairs": set()})
        per_stat[r["stat"]]["n_points"] += 1
        per_stat[r["stat"]]["n_in_likelihood"] += int(bool(r["in_likelihood"]))
        per_stat[r["stat"]]["pairs"].add((r["tr1"], r["tr2"]))
    for v in per_stat.values():
        v["n_pairs"] = len(v.pop("pairs"))
    metadata = {"computed_on": computed_on, "n_data": out["n_data"],
                "n_data_in_likelihood": out["n_data_likelihood"], "per_statistic": per_stat,
                "total_snr": snr, "cov_type": out["cov_type"], "scale_cuts_kept": out["scale_cuts"],
                "sacc_path": out["sacc_path"], "cov_file_is_full_matrix": cov is not None,
                "nz_zmean": {n: nz[n]["zmean"] for n in nz}, "versions": out.get("versions"),
                "timing_s": out.get("timing_s"), "validator_warnings": warns}
    if out.get("_env_check"):
        metadata["env_check"] = out["_env_check"]
    if out.get("_artifact_files"):
        metadata["remote_artifact_files"] = out["_artifact_files"]
    return ArtifactResult(
        status="success", files=files,
        message=f"Synthetic data vector: {out['n_data']} C_ell points ({out['n_data_likelihood']} inside "
                f"the scale cuts) with {out['cov_type']} covariance"
                + (f", total S/N {snr:.0f}" if snr else "") + f"; computed on {computed_on}.",
        metadata=metadata)


augur_generate_synthetic_datavector.weight = "dispatchable"


@validate_call
def augur_compute_fisher(
    output_dir: Annotated[str, Field(min_length=1)],
    config_path: Annotated[str, Field(min_length=1, description="Forecast YAML from augur_generate_forecast_config (validated, with a fisher section).")],
    env_setup: Annotated[str | None, Field(description="Facility environment activation when dispatch is remote (export_dispatch_pack lists candidates); ignored locally.")] = None,
    include_bias: Annotated[bool | None, Field(description="Compute the Fisher bias when the config has fisher.fisher_bias (None = yes if present).")] = None,
    derived_params: Annotated[bool, Field(description="Also report sigma(Omega_m) and sigma(S8) by linear propagation when Omega_c / sigma8 are varied.")] = True,
    duration_s: Annotated[int, Field(ge=300, le=28800, description="Walltime for a remote job (2n+1 evaluations; eisenstein_hu ~1 s each for 3x2pt Y1, CAMB ~5 s).")] = 1800,
) -> ArtifactResult:
    """Compute the Fisher matrix (augur.Analyze) -> fisher.csv, priors, marginalised sigmas, w0-wa FoM, derivatives.

    HEAVY: 2n+1 (numdifftools) / 4n+1 (5pt_stencil) full theory-vector
    evaluations for n varied parameters; Y1 3x2pt with eisenstein_hu is ~1 s
    per evaluation, CAMB ~5 s, Y10 roughly twice. Dispatch with env_setup on
    a facility for large runs. Outputs in <output_dir>: fisher_<slug>.csv
    (labelled matrix, fiducials and priors in the header), fisher_with_priors_<slug>.csv
    (when gaussian_priors exist), marginalized_sigmas_<slug>.csv (param,
    fiducial, sigma_no_prior, sigma_with_prior, prior), fom_<slug>.json (DETF
    FoM 1/sqrt(det Cov_w0wa), augur's get_FoM_all at 68/95%, with and without
    priors, plus Omega_m/S8 derived sigmas), derivatives_<slug>.npy (n_par x
    n_data), fisher_bias_<slug>.csv when requested. Checks symmetry and
    positive-definiteness (a non-PD matrix means a degenerate or noisy
    derivative - change step or var_pars). Next: augur_plot_fisher_contours.
    """
    cfg = _load_config(config_path)
    errors, warns, info = _validate(cfg)
    if errors:
        raise ValueError("config fails validation (run augur_validate_forecast_config): " + "; ".join(errors[:5]))
    if "fisher" not in cfg:
        raise ValueError("config has no fisher section")
    out, computed_on = _run_forecast_kernel(cfg, "fisher", env_setup, duration_s,
                                            include_bias=include_bias, max_cov_return=0)

    names = list(out["param_names"])
    F = np.asarray(out["fisher"], dtype=float)
    Fp = np.asarray(out["fisher_with_priors"], dtype=float) if out.get("fisher_with_priors") is not None else None
    fid = [float(v) for v in out["fiducials"]]
    priors = {k: float(v) for k, v in (out.get("priors") or {}).items()}
    # priors on transformed names keep the transformed label
    sym_err = float(np.max(np.abs(F - F.T)) / max(np.max(np.abs(F)), 1e-300))
    eig = np.linalg.eigvalsh(0.5 * (F + F.T))
    pos_def = bool(eig.min() > 0)
    cond = float(eig.max() / eig.min()) if pos_def else None
    cov = np.linalg.inv(F) if pos_def else np.linalg.pinv(F)
    sig = np.sqrt(np.clip(np.diag(cov), 0, None))
    sig_p = None
    if Fp is not None:
        covp = np.linalg.inv(Fp)
        sig_p = np.sqrt(np.clip(np.diag(covp), 0, None))

    outdir = resolve_outdir(output_dir)
    slug = param_slug({"cfg": str(Path(config_path).resolve()), "pars": tuple(names)})
    label = f"augur Fisher ({len(names)} params, {out['derivative_method']}, step {out['step']:g})"
    extra = [f"config: {config_path}", f"derivative_method: {out['derivative_method']}",
             f"step_absolute: {out['step']}", f"n_data: {out['n_data_likelihood']}",
             f"cov_type: {out['cov_type']}", f"computed_on: {computed_on}"]
    f_path = outdir / f"fisher_{slug}.csv"
    _write_fisher_csv(f_path, names, F, fid, priors, label, extra + ["priors_included: no"])
    files = [str(f_path)]
    fp_path = None
    if Fp is not None:
        fp_path = outdir / f"fisher_with_priors_{slug}.csv"
        _write_fisher_csv(fp_path, names, Fp, fid, priors, label + " + Gaussian priors", extra + ["priors_included: yes"])
        files.append(str(fp_path))
    ms_path = outdir / f"marginalized_sigmas_{slug}.csv"
    _write_table(ms_path, [f"label: marginalised 1-sigma errors ({label})", "quantity: marginalized_sigmas",
                           "units: parameter units; sigma = sqrt((F^-1)_ii)", f"config: {config_path}"],
                 {"param": names, "fiducial": fid, "sigma_no_prior": [float(s) for s in sig],
                  "sigma_with_prior": [float(s) for s in sig_p] if sig_p is not None else [float("nan")] * len(names),
                  "prior": [priors.get(n, float("nan")) for n in names]})
    files.append(str(ms_path))
    d_path = outdir / f"derivatives_{slug}.npy"
    np.save(d_path, np.asarray(out["derivatives"], dtype=float))
    files.append(str(d_path))

    cosmo_fid = dict(cfg.get("cosmo") or {})
    fom = {"params": names, "fiducials": dict(zip(names, fid)),
           "sigma_no_prior": dict(zip(names, map(float, sig))),
           "sigma_with_prior": dict(zip(names, map(float, sig_p))) if sig_p is not None else None,
           "priors": priors, "no_prior": _fom_block(F, names) if pos_def else None,
           "with_prior": _fom_block(Fp, names) if Fp is not None else None,
           "fom_definition": "DETF: 1/sqrt(det Cov(w0,wa)) with Cov = F^-1 marginalised over all other "
                             "parameters; augur_get_FoM_all scales Cov by chi2.ppf(CL,2) (= DETF/scale)",
           "derived": {}}
    if derived_params and not (out.get("transform_S8") or out.get("transform_Omega_m")):
        fom["derived"]["no_prior"] = _derived_sigmas(F, names, cosmo_fid) if pos_def else {}
        if Fp is not None:
            fom["derived"]["with_prior"] = _derived_sigmas(Fp, names, cosmo_fid)
    fom_path = outdir / f"fom_{slug}.json"
    write_json(fom_path, fom)
    files.append(str(fom_path))
    bias_meta = None
    if out.get("bias"):
        b = out["bias"]
        shift = np.asarray(b["shift"], dtype=float)
        b_path = outdir / f"fisher_bias_{slug}.csv"
        _write_table(b_path, [f"label: Fisher bias ({label})", "quantity: fisher_bias",
                              "units: parameter units; bias_over_sigma uses the no-prior sigma",
                              f"bias_params: {b['bias_params']}"],
                     {"param": names, "fiducial": fid, "bias": [float(x) for x in shift],
                      "sigma_no_prior": [float(s) for s in sig],
                      "bias_over_sigma": [float(x / s) if s > 0 else float("nan") for x, s in zip(shift, sig)]})
        files.append(str(b_path))
        bias_meta = {"bias_params": b["bias_params"], "shift": dict(zip(names, map(float, shift))),
                     "shift_over_sigma": {n: float(x / s) if s > 0 else None for n, x, s in zip(names, shift, sig)}}
    sacc_local = out["sacc_path"] if computed_on == "local" and os.path.isfile(out["sacc_path"]) else None
    if sacc_local:
        files.append(sacc_local)

    metadata = {"computed_on": computed_on, "params": names, "fiducials": dict(zip(names, fid)),
                "sigma_no_prior": fom["sigma_no_prior"], "sigma_with_prior": fom["sigma_with_prior"],
                "priors": priors, "fom": {"no_prior": fom["no_prior"], "with_prior": fom["with_prior"]},
                "derived": fom["derived"], "fisher_bias": bias_meta,
                "checks": {"symmetric_rel_err": sym_err, "positive_definite": pos_def,
                           "condition_number": cond, "min_eigenvalue": float(eig.min())},
                "n_data": out["n_data_likelihood"], "n_evaluations": out["n_evaluations"],
                "derivative_method": out["derivative_method"], "step_absolute": out["step"],
                "cov_type": out["cov_type"], "timing_s": out.get("timing_s"), "versions": out.get("versions"),
                "augur_text_outputs": [out.get("augur_output"), out.get("augur_fid_output")],
                "validator_warnings": warns}
    if out.get("_env_check"):
        metadata["env_check"] = out["_env_check"]
    if out.get("_artifact_files"):
        metadata["remote_artifact_files"] = out["_artifact_files"]
    sig_txt = ", ".join(f"{n}={s:.3g}" for n, s in zip(names, sig))
    msg = (f"Fisher matrix for {len(names)} parameters from {out['n_data_likelihood']} data points "
           f"({out['n_evaluations']} evaluations, {out.get('timing_s', {}).get('fisher', 0):.0f} s on {computed_on}). "
           f"Marginalised sigma (no prior): {sig_txt}.")
    if fom["no_prior"] and fom["no_prior"].get("detf_fom"):
        msg += f" DETF w0-wa FoM: {fom['no_prior']['detf_fom']:.1f}"
        if fom["with_prior"] and fom["with_prior"].get("detf_fom"):
            msg += f" (with priors {fom['with_prior']['detf_fom']:.1f})"
        msg += "."
    if not pos_def:
        msg += " WARNING: Fisher matrix is not positive definite (degenerate parameters or noisy derivatives)."
    return ArtifactResult(status="success", files=files, message=msg, metadata=metadata)


augur_compute_fisher.weight = "heavy"


@validate_call
def augur_plot_fisher_contours(
    output_dir: Annotated[str, Field(min_length=1)],
    fisher_csvs: Annotated[list[str], Field(min_length=1, max_length=6, description="One or more fisher*.csv from augur_compute_fisher (overlaid; e.g. Y1 vs Y10, or without/with priors).")],
    params: Annotated[list[str] | None, Field(description="Parameter subset to show (order kept); None = all parameters of the first file (<= 8 recommended).")] = None,
    labels: Annotated[list[str] | None, Field(description="Legend label per file; None = the file's label header.")] = None,
    confidence_levels: Annotated[list[float], Field(description="Ellipse confidence levels (2D), e.g. [0.68, 0.95].")] = [0.68, 0.95],
    fiducials: Annotated[dict[str, float] | None, Field(description="Override the ellipse centres (default: fiducials stored in the CSV header).")] = None,
    title: Annotated[str | None, Field()] = None,
) -> ArtifactResult:
    """Triangle plot of Fisher ellipses (68/95% CL) for a parameter subset, overlaying several Fisher matrices.

    Marginalises each file's Fisher matrix over the parameters not shown
    (Cov = F^-1, then the 2x2 sub-blocks) and draws the CL ellipses with
    augur's scaling (chi2.ppf(CL, 2)), 1-D Gaussians on the diagonal.
    Parameters missing from a file are skipped for that file. Writes
    fisher_contours_<slug>.png. Metadata: per file the marginalised sigmas of
    the shown parameters and the DETF w0-wa FoM when both are present, and
    FoM ratios relative to the first file (e.g. Y10/Y1).
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.patches import Ellipse
    from scipy.stats import norm
    from ..plotting import LINESTYLES, PALETTE, rc_params

    for cl in confidence_levels:
        if not (0 < cl < 1):
            raise ValueError("confidence_levels must be in (0, 1)")
    loaded = []
    for k, p in enumerate(fisher_csvs):
        names, F, fid, header = read_fisher_csv(p)
        if fiducials:
            fid.update({n: float(v) for n, v in fiducials.items() if n in fid})
        lab = labels[k] if labels and k < len(labels) else header.get("label", Path(p).stem)
        loaded.append({"path": p, "names": names, "F": F, "fid": fid, "label": lab})
    show = params or list(loaded[0]["names"])
    missing = [n for n in show if n not in loaded[0]["names"]]
    if missing:
        raise ValueError(f"params {missing} not in {fisher_csvs[0]} (has {loaded[0]['names']})")
    if len(show) < 1:
        raise ValueError("need at least one parameter")

    summary = []
    for entry in loaded:
        cov = np.linalg.inv(entry["F"])
        idx = {n: entry["names"].index(n) for n in show if n in entry["names"]}
        entry["cov"] = cov
        entry["idx"] = idx
        sig = {n: float(np.sqrt(cov[i, i])) for n, i in idx.items()}
        fom = _fom_block(entry["F"], entry["names"])
        summary.append({"file": entry["path"], "label": entry["label"], "sigma": sig,
                        "detf_fom_w0wa": fom["detf_fom"] if fom else None})
    npar = len(show)
    with plt.rc_context(rc_params(10)):
        size = max(2.0, min(3.2, 14 / npar))
        fig, axes = plt.subplots(npar, npar, figsize=(size * npar, size * npar), squeeze=False)
        lims = {}
        for n in show:
            s_max = max((e["cov"][e["idx"][n], e["idx"][n]] ** 0.5 for e in loaded if n in e["idx"]), default=1.0)
            c = loaded[0]["fid"].get(n, 0.0)
            lims[n] = (c - 3.2 * s_max, c + 3.2 * s_max)
        for i, pi in enumerate(show):
            for j, pj in enumerate(show):
                ax = axes[i, j]
                if j > i:
                    ax.set_visible(False)
                    continue
                for k, e in enumerate(loaded):
                    color = PALETTE[k % len(PALETTE)]
                    ls = LINESTYLES[k % len(LINESTYLES)]
                    if pi not in e["idx"] or pj not in e["idx"]:
                        continue
                    ci, cj = e["fid"].get(pi, 0.0), e["fid"].get(pj, 0.0)
                    if i == j:
                        s = np.sqrt(e["cov"][e["idx"][pi], e["idx"][pi]])
                        x = np.linspace(*lims[pi], 300)
                        ax.plot(x, norm.pdf(x, ci, s) * s, color=color, ls=ls, label=e["label"] if i == 0 else None)
                    else:
                        ii, jj = e["idx"][pi], e["idx"][pj]
                        sub = e["cov"][np.ix_([jj, ii], [jj, ii])]
                        for m, cl in enumerate(sorted(confidence_levels)):
                            w, h, ang = _ellipse(sub, cl)
                            ax.add_patch(Ellipse((cj, ci), w, h, angle=ang, facecolor=color,
                                                 edgecolor=color, ls=ls, lw=1.3,
                                                 alpha=0.35 if m == 0 else 0.15))
                        ax.plot([cj], [ci], marker="+", color=color, ms=5, mew=0.8)
                if i == j:
                    ax.set_yticks([])
                    ax.set_xlim(*lims[pi])
                    ax.set_ylim(0, 0.45)
                else:
                    ax.set_xlim(*lims[pj])
                    ax.set_ylim(*lims[pi])
                if i == npar - 1:
                    ax.set_xlabel(_label_of(pj))
                else:
                    ax.set_xticklabels([])
                if j == 0 and i > 0:
                    ax.set_ylabel(_label_of(pi))
                elif j > 0:
                    ax.set_yticklabels([])
                ax.tick_params(labelsize=7)
                ax.xaxis.set_major_locator(plt.MaxNLocator(3))
                ax.yaxis.set_major_locator(plt.MaxNLocator(3))
        handles, labs = axes[0, 0].get_legend_handles_labels()
        if handles:
            fig.legend(handles, labs, loc="upper right", frameon=False, fontsize=9,
                       bbox_to_anchor=(0.98, 0.98))
        fig.suptitle(title or f"Fisher contours ({', '.join(f'{cl:.0%}' for cl in sorted(confidence_levels))} CL)",
                     fontsize=11, y=0.995)
        fig.subplots_adjust(wspace=0.08, hspace=0.08, left=0.1, bottom=0.1, right=0.98, top=0.95)
        outdir = resolve_outdir(output_dir)
        slug = param_slug({"files": tuple(fisher_csvs), "params": tuple(show), "cl": tuple(confidence_levels)})
        png = outdir / f"fisher_contours_{slug}.png"
        fig.savefig(png, dpi=160)
        plt.close(fig)

    ratios = {}
    base = summary[0]["detf_fom_w0wa"]
    if base:
        for s in summary[1:]:
            if s["detf_fom_w0wa"]:
                ratios[s["label"]] = float(s["detf_fom_w0wa"] / base)
    return ArtifactResult(
        status="success", files=[str(png)],
        message=f"Triangle plot for {npar} parameters from {len(loaded)} Fisher matrix(es) at "
                f"{', '.join(f'{cl:.0%}' for cl in sorted(confidence_levels))} CL.",
        metadata={"params": show, "confidence_levels": confidence_levels, "per_file": summary,
                  "fom_ratio_to_first": ratios,
                  "note": "sigmas are marginalised over ALL parameters of each Fisher matrix, not only the shown subset"})
