"""Smokescreen tools: data-vector concealment (blinding) with a firecrown likelihood.

Smokescreen (github.com/LSSTDESC/Smokescreen) implements the Muir et al.
(2021) scheme: the data vector is shifted by the difference (or ratio)
between the theory at a hidden cosmology and the theory at the reference
cosmology, so the analysis runs on a data vector whose cosmology is unknown
to the analyst. The hidden cosmology is drawn from the ranges you give with
a seed; everything that would reveal it (the drawn values, the seed) is
kept OUT of this server's outputs, messages and metadata.

This family builds on the firecrown family: the likelihood is the
experiment YAML from firecrown_build_likelihood (a tiny generated module
wraps it in the `build_likelihood` form Smokescreen expects). Originals are
never deleted or modified; concealed and encrypted files are new files in
output_dir. Package name `smokescreen_tools` avoids shadowing the library.
"""

import contextlib
import datetime as _dt
import sys
from pathlib import Path
from typing import Annotated, Literal

import numpy as np
from pydantic import Field, validate_call

from ..common import ArtifactResult, param_slug, resolve_outdir, write_json
from ..cosmology import CosmologyParams
from ..firecrown_tools import _check_point, _exp_path, _load_local, _sacc_path_from_yaml
from ..sacc_tools import _load as _load_sacc

__all__ = ["smokescreen_conceal_datavector", "smokescreen_inspect",
           "smokescreen_encrypt_file", "smokescreen_decrypt_file"]

CONVENTIONS = {
    "method": "Muir et al. 2021 data-vector concealment: d_concealed = d + [t(theta_hidden) - t(theta_ref)] "
              "(shift_type add) or d * t(theta_hidden)/t(theta_ref) (mult); t = firecrown theory vector",
    "shifts": "per cosmological parameter (pyccl names: Omega_c Omega_b h n_s sigma8|A_s Omega_k Neff m_nu w0 wa): "
              "[lo, hi] = hidden value drawn uniformly in [lo, hi] (ABSOLUTE values, not offsets) with "
              "shift_distribution 'flat'; [mean, std] with 'gaussian'; a single number = deterministic "
              "hidden value = reference + number (a test mode, not concealment)",
    "likelihood": "the experiment YAML from firecrown_build_likelihood; the experiment must keep EVERY point "
                  "of the sacc file (no scale cuts) because Smokescreen checks the data vector against the file",
    "seed": "any string or integer; the same seed, ranges and reference reproduce the same hidden cosmology - "
            "treat it as the secret. The tools never echo it; it does appear in the chat where you typed it",
    "outputs": "the concealed sacc carries metadata concealed=true, creator, creation, info; a record JSON "
               "lists the shifted parameters and ranges (never the drawn values)",
    "encryption": "Fernet (symmetric) via smokescreen.encryption: <stem>.encrpt + <stem>.key; originals kept",
}
CAVEATS = [
    "Smokescreen stores the seed in the concealed file's metadata (seed_smokescreen) - upstream behaviour. "
    "With the ranges, that reproduces the hidden cosmology: do not share the concealed file together with "
    "the ranges and expect concealment to hold. smokescreen_inspect flags it.",
    "Nuisance parameters are held at the reference values for both theory evaluations (firecrown "
    "defaults made neutral, overridden by `nuisance`); only cosmological parameters are concealed.",
    "The amplitude parameter you shift (sigma8 or A_s) must be the one the experiment samples "
    "(firecrown_build_likelihood amplitude_parameter); a sigma8 shift on an A_s experiment is refused.",
    "A multiplicative shift divides by the reference theory: zero-crossing statistics (xi_-, cross spectra) "
    "make it ill-defined - prefer 'add' for 3x2pt.",
    "A deterministic single-value shift is reproducible by construction - use it only to validate a pipeline.",
    "Originals are never deleted by these tools (Smokescreen's CLI deletes them by default); delete or "
    "move the original yourself if the analysis protocol requires it.",
]

_CCL_PARAMS = ("Omega_c", "Omega_b", "h", "n_s", "sigma8", "A_s", "Omega_k", "Neff", "m_nu", "w0", "wa")

_LIKELIHOOD_MODULE = '''"""firecrown likelihood module generated by desc-mcp-server (smokescreen_conceal_datavector).

Wraps a TwoPointExperiment YAML in the build_likelihood() form Smokescreen
expects. The sacc file comes from the YAML (data_source.sacc_data_file);
build_parameters is accepted for the interface and otherwise unused.
"""
EXPERIMENT_YAML = {yaml!r}


def build_likelihood(build_parameters=None):
    import warnings

    from firecrown.likelihood.factories import TwoPointExperiment
    from firecrown.modeling_tools import ModelingTools

    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        exp = TwoPointExperiment.load_from_yaml(EXPERIMENT_YAML)
        like = exp.make_likelihood()
        tools = ModelingTools(ccl_factory=exp.ccl_factory)
    return like, tools
'''


def _amplitude_of(exp_path: Path) -> str:
    import yaml

    doc = yaml.safe_load(exp_path.read_text(encoding="utf-8")) or {}
    amp = str(((doc.get("ccl_factory") or {}).get("amplitude_parameter") or "sigma8")).lower()
    return "A_s" if amp in ("a_s", "as") else "sigma8"


def _sniff_format(data: bytes) -> str:
    if data[:8] == b"\x89HDF\r\n\x1a\n":
        return "hdf5"
    if data[:6] == b"SIMPLE":
        return "fits"
    return "unknown"


# --------------------------------------------------------------------------
# tools
# --------------------------------------------------------------------------
@validate_call
def smokescreen_conceal_datavector(
    output_dir: Annotated[str, Field(min_length=1)],
    experiment_yaml: Annotated[str, Field(min_length=1, description="firecrown experiment YAML (firecrown_build_likelihood) covering every point of its sacc file.")],
    shifts: Annotated[dict[str, float | list[float]], Field(description="Hidden-cosmology ranges per parameter: {'Omega_c': [0.20, 0.32], 'sigma8': [0.72, 0.90], 'w0': [-1.3, -0.7]} (absolute values; 'gaussian' => [mean, std]); a single number = deterministic offset (test mode).")],
    seed: Annotated[int | str, Field(description="Seed of the hidden draw (int or any string); the secret - never echoed by the tools.")],
    shift_type: Annotated[Literal["add", "mult"], Field(description="Additive (recommended for 3x2pt) or multiplicative concealing factor.")] = "add",
    shift_distribution: Annotated[Literal["flat", "gaussian"], Field(description="How the hidden values are drawn from the ranges.")] = "flat",
    reference_cosmology: Annotated[CosmologyParams | None, Field(description="Reference cosmology theta_ref (None = vanilla LCDM). Its amplitude parameter must match the experiment's.")] = None,
    nuisance: Annotated[dict[str, float], Field(description="Nuisance values held fixed for both theory evaluations (unspecified ones take neutral/firecrown defaults, as in firecrown_compute_loglike).")] = {},
    output_format: Literal["same", "hdf5", "fits"] = "same",
    output_suffix: Annotated[str, Field(min_length=1, description="Suffix of the concealed file: <stem>_<suffix>.<ext>.")] = "concealed",
    encrypt_original: Annotated[bool, Field(description="Also write an encrypted copy of the original sacc (+ key) into output_dir; the original is kept.")] = False,
) -> ArtifactResult:
    """Conceal (blind) a sacc data vector with Smokescreen: shift it by the firecrown theory difference between a hidden cosmology (drawn from your ranges with the seed) and the reference cosmology.

    Steps: validate the ranges against pyccl parameter names and the
    experiment's amplitude parameter; check the experiment uses every
    point of the sacc; generate a build_likelihood module wrapping the
    experiment YAML; run ConcealDataVector (two theory evaluations); write
    <stem>_<suffix>.<ext> (sacc metadata: concealed=true, creator, creation,
    info) plus <stem>_concealment_record.json naming the shifted parameters,
    ranges, distribution, type and reference cosmology - never the drawn
    values. Point firecrown_build_likelihood at the concealed file to analyse
    it. The original file is untouched (encrypt_original adds an encrypted
    copy + key; nothing is deleted). Local, seconds (one 3x2pt theory
    vector ~0.4 s).
    """
    exp_path = _exp_path(experiment_yaml)
    outdir = resolve_outdir(output_dir)
    spath = _sacc_path_from_yaml(exp_path)
    if not spath.is_file():
        raise ValueError(f"sacc file referenced by {exp_path.name} not found: {spath}")
    if not shifts:
        raise ValueError("shifts must name at least one cosmological parameter.")
    bad = sorted(k for k in shifts if k not in _CCL_PARAMS)
    if bad:
        raise ValueError(f"shifts for non-cosmological names {bad}; allowed: {list(_CCL_PARAMS)} "
                         "(Smokescreen conceals cosmological parameters only).")
    amp = _amplitude_of(exp_path)
    other = "sigma8" if amp == "A_s" else "A_s"
    if other in shifts:
        raise ValueError(f"the experiment samples {amp}, so a {other} shift cannot be applied; shift {amp} instead "
                         f"(or rebuild with firecrown_build_likelihood(amplitude_parameter='{other}')).")
    spec = reference_cosmology or CosmologyParams()
    if amp == "A_s" and spec.A_s is None:
        raise ValueError("the experiment samples A_s: give reference_cosmology with A_s (and sigma8: null).")
    if amp == "sigma8" and spec.sigma8 is None:
        raise ValueError("the experiment samples sigma8: give reference_cosmology with sigma8.")

    shifts_py: dict = {}
    ranges: dict = {}
    for k, v in shifts.items():
        if isinstance(v, (list, tuple)):
            if len(v) != 2:
                raise ValueError(f"shift for {k} must be [lo, hi] (or [mean, std]), got {v}")
            lo, hi = float(v[0]), float(v[1])
            if shift_distribution == "flat" and not lo < hi:
                raise ValueError(f"shift range for {k} needs lo < hi: {v}")
            if shift_distribution == "gaussian" and hi <= 0:
                raise ValueError(f"gaussian shift for {k} needs std > 0: {v}")
            shifts_py[k] = (lo, hi)
            ranges[k] = {"kind": "uniform" if shift_distribution == "flat" else "gaussian",
                         ("range" if shift_distribution == "flat" else "mean_std"): [lo, hi]}
        else:
            shifts_py[k] = float(v)
            ranges[k] = {"kind": "deterministic_offset", "offset": float(v)}
    deterministic = [k for k, r in ranges.items() if r["kind"] == "deterministic_offset"]

    like, tools, sacc_data = _load_local(exp_path)
    from ..inner.firecrown_loglike import required_defaults

    required = required_defaults(like, tools)
    n_like = int(len(np.asarray(like.get_data_vector())))
    n_file = int(len(sacc_data.data))
    if n_like != n_file:
        raise ValueError(f"the experiment uses {n_like} of the file's {n_file} points (scale cuts / dropped "
                         "data types): Smokescreen needs the likelihood to cover the whole file. Build the "
                         "experiment without cuts, or first write a reduced sacc with "
                         "sacc_prepare_for_firecrown(keep_data_types=...) and build on that.")
    point, warns = _check_point(required, spec, nuisance, exp_path)
    like_names = list(like.required_parameters().get_params_names())
    systematics = {k: float(point[k]) for k in like_names if k in point}
    missing = [k for k in like_names if k not in systematics]
    if missing:  # firecrown defaults for anything _check_point did not place
        for k in missing:
            systematics[k] = float(required[k]) if not isinstance(required[k], list) else required[k]

    import pyccl as ccl

    ref_cosmo = ccl.Cosmology(**spec.ccl_kwargs())

    slug = param_slug({"exp": str(exp_path), "params": ",".join(sorted(shifts)), "type": shift_type,
                       "dist": shift_distribution, "ref": spec.slug()})
    mod_path = outdir / f"likelihood_{exp_path.stem}_{slug}.py"
    mod_path.write_text(_LIKELIHOOD_MODULE.format(yaml=str(exp_path)), encoding="utf-8")

    from smokescreen import ConcealDataVector
    from smokescreen.utils import load_sacc_file

    sacc_obj, in_format = load_sacc_file(str(spath))
    with contextlib.redirect_stdout(sys.stderr):
        smoke = ConcealDataVector(ref_cosmo, str(mod_path), shifts_py, sacc_obj, systematics, seed,
                                  shift_distr=shift_distribution, input_format=in_format)
        smoke.calculate_concealing_factor(factor_type=shift_type)
        smoke.apply_concealing_to_likelihood_datavec()
        fmt = in_format if output_format == "same" else output_format
        stem = spath.stem.replace(".sacc", "")
        smoke.save_concealed_datavector(str(outdir), stem, output_format=fmt, suffix=output_suffix)
    out_path = outdir / f"{stem}_{output_suffix}{'.hdf5' if fmt == 'hdf5' else '.fits'}"
    if not out_path.is_file():
        raise RuntimeError(f"Smokescreen reported success but {out_path} was not written")
    del smoke  # drop the object holding the hidden cosmology

    concealed = _load_sacc(str(out_path))
    meta = {k: (v if isinstance(v, (int, float, str, bool)) else str(v)) for k, v in concealed.metadata.items()
            if k != "seed_smokescreen"}
    record = {"concealed_file": str(out_path), "original_file": str(spath), "experiment_yaml": str(exp_path),
              "likelihood_module": str(mod_path), "shifted_parameters": sorted(shifts), "ranges": ranges,
              "shift_type": shift_type, "shift_distribution": shift_distribution,
              "reference_cosmology": spec.firecrown_params(), "nuisance_fixed": systematics,
              "n_points": n_file, "created": _dt.datetime.now().isoformat(timespec="seconds"),
              "sacc_metadata": meta, "seed": "withheld (never recorded by this server)",
              "note": "the drawn hidden values are not recorded anywhere by this server"}
    rpath = outdir / f"{stem}_concealment_record.json"
    write_json(rpath, record)
    files = [str(out_path), str(rpath), str(mod_path)]

    if encrypt_original:
        from smokescreen.encryption import encrypt_file

        blob, key = encrypt_file(str(spath), save_file=False, keep_original=True)
        epath = outdir / f"{stem}.encrpt"
        kpath = outdir / f"{stem}.key"
        epath.write_bytes(blob)
        kpath.write_bytes(key)
        files += [str(epath), str(kpath)]

    msg = (f"Wrote {out_path.name}: {n_file} points concealed ({shift_type}, {shift_distribution} draw over "
           f"{sorted(shifts)}, reference {spec.label()}). The hidden cosmology and the seed are not recorded. "
           f"Analyse it with firecrown_build_likelihood(sacc_path='{out_path}').")
    if deterministic:
        msg += f" NOTE: deterministic offsets for {deterministic} are reproducible - a pipeline test, not concealment."
    if encrypt_original:
        msg += f" Original encrypted to {epath.name} (key {kpath.name}); the original file itself is untouched."
    if warns:
        msg += " Notes: " + " | ".join(warns)
    return ArtifactResult(
        status="success", files=files, message=msg,
        metadata={k: v for k, v in record.items() if k not in ("nuisance_fixed",)} | {
            "warnings": warns, "deterministic_parameters": deterministic,
            "next_step": "firecrown_build_likelihood on the concealed file; keep the record JSON with it"},
    )


@validate_call
def smokescreen_inspect(
    output_dir: Annotated[str, Field(min_length=1)],
    sacc_path: Annotated[str, Field(min_length=1, description="A sacc file (concealed or not) or a Smokescreen .encrpt file.")],
    compare_with: Annotated[str | None, Field(description="PIPELINE-TEST ONLY: the original sacc, to quantify the applied shift per data type (reveals the concealment!).")] = None,
) -> ArtifactResult:
    """Report whether a sacc file is Smokescreen-concealed (metadata concealed/creator/creation/info, whether a seed is embedded) or encrypted, without revealing anything hidden.

    For an .encrpt file: size and that a .key is needed. For a sacc: the
    concealment flags, point count and whether the embedded seed is present
    (Smokescreen writes seed_smokescreen; with the ranges it reproduces the
    hidden cosmology - keep such files with their record JSON away from the
    ranges if that matters). compare_with (original file) prints the RMS
    fractional shift per data type - only for validating a pipeline on test
    data, since it reveals the concealing factor.
    """
    p = Path(sacc_path).expanduser().resolve()
    if not p.is_file():
        raise ValueError(f"file not found: {p}")
    outdir = resolve_outdir(output_dir)
    head = p.read_bytes()[:16]
    if p.suffix == ".encrpt" or _sniff_format(head) == "unknown":
        info = {"file": str(p), "encrypted": True, "bytes": p.stat().st_size,
                "key_expected": str(p.with_suffix(".key"))}
        return ArtifactResult(status="success", files=[], metadata=info,
                              message=f"{p.name} is not a readable sacc ({p.stat().st_size} bytes): a Smokescreen "
                                      f".encrpt file (decrypt with smokescreen_decrypt_file and its .key) or not a sacc at all.")
    s = _load_sacc(str(p))
    meta = {k: (v if isinstance(v, (int, float, str, bool)) else str(v)) for k, v in s.metadata.items()}
    concealed = bool(meta.get("concealed", False))
    info = {"file": str(p), "encrypted": False, "concealed": concealed, "n_points": len(s.data),
            "creator": meta.get("creator"), "creation": meta.get("creation"), "info": meta.get("info"),
            "seed_embedded": "seed_smokescreen" in meta, "tjpcov_cov_types": meta.get("tjpcov_cov_types"),
            "metadata_keys": sorted(meta)}
    files = []
    if compare_with:
        o = _load_sacc(compare_with)
        if len(o.data) != len(s.data):
            raise ValueError(f"compare_with has {len(o.data)} points, this file {len(s.data)}")
        a = np.asarray(s.mean, float)
        b = np.asarray(o.mean, float)
        per_type = {}
        for dt in s.get_data_types():
            idx = np.array([i for i, d in enumerate(s.data) if d.data_type == dt])
            with np.errstate(invalid="ignore", divide="ignore"):
                frac = (a[idx] - b[idx]) / b[idx]
            frac = frac[np.isfinite(frac)]
            per_type[dt] = {"rms_fractional_shift": float(np.sqrt(np.mean(frac ** 2))) if len(frac) else None,
                            "max_abs_fractional_shift": float(np.max(np.abs(frac))) if len(frac) else None}
        info["comparison"] = {"original": str(Path(compare_with).expanduser().resolve()), "per_data_type": per_type,
                              "warning": "this comparison reveals the concealing factor - test data only"}
        cpath = outdir / f"{p.stem}_shift_vs_original.json"
        write_json(cpath, info["comparison"])
        files.append(str(cpath))
    msg = (f"{p.name}: {'CONCEALED' if concealed else 'not concealed'} ({len(s.data)} points"
           + (f", created {meta.get('creation')} by {meta.get('creator')}" if concealed else "")
           + (", seed embedded in metadata" if info["seed_embedded"] else "") + ").")
    if compare_with:
        rms = {k: round(v["rms_fractional_shift"], 4) for k, v in info["comparison"]["per_data_type"].items()
               if v["rms_fractional_shift"] is not None}
        msg += f" RMS fractional shift vs original by data type: {rms} (test data only)."
    return ArtifactResult(status="success", files=files, message=msg, metadata=info)


@validate_call
def smokescreen_encrypt_file(
    output_dir: Annotated[str, Field(min_length=1)],
    path: Annotated[str, Field(min_length=1, description="File to encrypt (typically the original, unconcealed sacc).")],
) -> ArtifactResult:
    """Encrypt a file with Smokescreen's Fernet scheme into output_dir (<stem>.encrpt + <stem>.key); the original is kept.

    Use it to lock the unconcealed data vector away during a concealed
    analysis. Keep the .key separately: whoever holds it can decrypt. The
    original is NOT deleted (Smokescreen's CLI would) - remove it yourself
    if your protocol requires it.
    """
    from smokescreen.encryption import encrypt_file

    p = Path(path).expanduser().resolve()
    if not p.is_file():
        raise ValueError(f"file not found: {p}")
    outdir = resolve_outdir(output_dir)
    blob, key = encrypt_file(str(p), save_file=False, keep_original=True)
    stem = p.stem.replace(".sacc", "")
    epath = outdir / f"{stem}.encrpt"
    kpath = outdir / f"{stem}.key"
    epath.write_bytes(blob)
    kpath.write_bytes(key)
    return ArtifactResult(
        status="success", files=[str(epath), str(kpath)],
        message=f"Encrypted {p.name} -> {epath.name} ({len(blob)} bytes); key in {kpath.name}. Original kept.",
        metadata={"original": str(p), "encrypted": str(epath), "key": str(kpath), "bytes": len(blob),
                  "original_format": _sniff_format(p.read_bytes()[:16])},
    )


@validate_call
def smokescreen_decrypt_file(
    output_dir: Annotated[str, Field(min_length=1)],
    path: Annotated[str, Field(min_length=1, description="The .encrpt file.")],
    key_path: Annotated[str, Field(min_length=1, description="The matching .key file.")],
    output_name: Annotated[str | None, Field(description="Name of the decrypted file; default <stem>_decrypted.<hdf5|fits> by content.")] = None,
) -> ArtifactResult:
    """Decrypt a Smokescreen .encrpt file with its key into output_dir (extension chosen from the content: hdf5 / fits).

    The encrypted file and the key are left in place. The result is the
    original data vector - handle it according to your concealment
    protocol.
    """
    from smokescreen.encryption import decrypt_file

    p = Path(path).expanduser().resolve()
    k = Path(key_path).expanduser().resolve()
    if not p.is_file():
        raise ValueError(f"file not found: {p}")
    if not k.is_file():
        raise ValueError(f"key not found: {k}")
    outdir = resolve_outdir(output_dir)
    blob = decrypt_file(str(p), str(k), save_file=False)
    fmt = _sniff_format(blob[:16])
    ext = {"hdf5": ".hdf5", "fits": ".fits"}.get(fmt, ".bin")
    out = outdir / (output_name or f"{p.stem}_decrypted{ext}")
    out.write_bytes(blob)
    return ArtifactResult(
        status="success", files=[str(out)],
        message=f"Decrypted {p.name} -> {out.name} ({len(blob)} bytes, {fmt}).",
        metadata={"encrypted": str(p), "key": str(k), "decrypted": str(out), "format": fmt, "bytes": len(blob)},
    )
